withfig/autocomplete

specs/dig.js

Added dig command autocomplete. 

---

specs/vercel.js

Added spec for Vercel CLI following https://vercel.com/docs/cli#commands/

Add vercel spec

---

specs/chmod.js

https://linear.app/fig/issue/ENG-115/build-chmod-completion-spec
Signed-off-by: James Jackson <james.sorley.jackson@gmail.com>

ENG-115: Build `chmod` completion spec

---

specs/clear.js
specs/head.js
specs/mkdir.js
specs/ps.js
specs/pwd.js
specs/top.js
specs/touch.js
specs/whois.js

Feature
Added new specs based on the new spec generator:
- clear
- head
- mkdir
- ps
- pwd
- top
- touch
- whois

Add generated system specs

---

.gitignore
specs/docker.js

Adds a number of `docker` CLI subcommands and flags
Not present
* `docker build`
* `docker ps`
* `docker images`
* `docker rm`
* `docker rmi`
* `docker stop`
* `docker inspect`
* `docker system`
* `docker version`
<3 Fig

Add in many more Docker CLI commands

---

specs/git.js

The pull request adds the autocompletion for git stash.
There are still 5 TODO's left that I could not fix.

update git stash

---

specs/knex.js

feature - add knex commands autocomplete
No knex completionSpec
knex completionSpec with up option

initial commit - created knex.js file

---

specs/knex.js
specs/wrk.js

Feature
Currently the cli for the wrk HTTP benchmarking tool isn't supported (https://github.com/wg/wrk)
With the pr we add support for the wrk cli commands.

Adding autocomplete specifications for wrk

---

specs/gh.js

Add PR suggestions in gh specs

Add PR suggestions in gh specs

---

dev/fig.ts
dev/git.ts
specs/fig.js
specs/git.js

Add fig settings and more git flags

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/cli_request.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/other.md

Adds new Issue Templates for this repo
There are no templates in place
There are different templates for different occasions

feat: add templates

---

dev/fig.ts
dev/git.ts
specs/fig.js
specs/git.js

update fig and git

---

dev/lerna.ts
specs/lerna.js

Feature
There is no completion spec for [lerna](https://github.com/lerna/lerna)
It adds the completion spec 🥳 

feat: add lerna command

---

dev/fig.ts
specs/fig.js

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)** 
Add fig setting for autocomplete.theme

add theme setting

---

dev/git.ts
specs/git.js

Feature.
See #77
Change icon and update description for current branch suggestion.

feat: indicate current branch in git

---

package.json
scripts/create-boilerplate.sh
scripts/dev.sh

dumb me: https://github.com/npm/cli/issues/2033

replace init_cwd with pwd

---

dev/grex.ts
specs/grex.js

Add specs for [grex](https://github.com/pemistahl/grex)

Add grex specs

---

dev/kubectl.ts
specs/kubectl.js

Feature
No generators for individual resources
Generators for resources & applied to subcommands

Kubectl resource generators

---

dev/fig.ts
specs/fig.js

add hideMenubarIcon setting

---

dev/git.ts
specs/git.js

Feature
Show default icon.
Show relevant icon depending on where the git remote is hosted. See #114 for details.
Do not merge until build v1.0.40 is live (and probably wait until v1.0.41) to ensure that majority of users have the new icons.

git: add icons to remote

---

dev/git.ts
scripts/eslint-plugin-fig-linter/index.js
scripts/eslint-plugin-fig-linter/rules/no-invalid-name.js
scripts/eslint-plugin-fig-linter/rules/no-invalid-option.js
scripts/eslint-plugin-fig-linter/rules/no-malicious-script.js
scripts/eslint-plugin-fig-linter/rules/no-name-equals.js
specs/git.js

Feature
The `name` prop isn't validated for subcommands and options
There are two new eslint rules which check and validate the `name` prop
There are a lot of failing specs now

[FIG] feat: add new eslint rules

---

.github/workflows/update-docs.yml

Feature
The docs need to be updated manually when we change the `fig.d.ts` file.
As soon as there is a new change in the `fig.d.ts` file in the master branch the docs will be updated
The code for the docs parser can be found here https://github.com/withfig/docs-parser
It is really ugly and hacky code though! 😆

[FIG]: feat: create docs from fig.d.ts

---

dev/fig.ts
specs/fig.js

Add the sortMethod setting to the Fig spec

[FIG] feat: add sortMethod setting

---

dev/fig.ts
specs/fig.js

add fuzzySearch setting

---

dev/rails.ts
specs/rails.js

Feature
There is no autocompletion for the Rails CLI
Introduces autocompletion for Rails CLI—the CLI has a lot of subcommands which can be generated depending on gems the user has installed, so it's often hard to remember all the commands.
- Could be nice to add an official Ruby icon
- Currently the autocomplete is super slow, as the Rails CLI itself is pretty slow to generate help commands. Open to ideas on how to speed this up or other UX improvements.

[RAILS] Add spec for Rails CLI

---

dev/heroku.ts
specs/heroku.js

Feature
The current heroku cli spec is lacking a lot of subcommands
This is an autogenerated spec created from the source code

[HEROKU] feat: add autogenerated heroku spec

---

dev/exa.ts
specs/exa.js

Added new spec for exa 
There isn't any spec for exa
This PR adds the exa

[EXA] Add spec for exa

---

dev/next.ts
specs/next.js

Adds the spec for Next.js's CLI
There isn't any spec for Next.js's CLI
This PR adds the Next.js CLI

[NEXT] Add spec for Next.js CLI

---

dev/sudo.ts
specs/sudo.js

Add spec for `sudo` 
#176 
Show autocompletes after `sudo`

[Sudo] feat: Add sudo spec

---

dev/ng.ts
specs/ng.js

Initial Angular spec with a few commands partially implemented.
Currently, there is no Angular spec.
Definitions for creating a Angular project as well as generating libraries, applications, components, and classes.

[NG] Initial Angular spec

---

dev/nx.ts
specs/nx.js

Feature
Fig currently has no spec for use with the Nx CLI.
Introduces autocomplete support for the Nx CLI. The CLI has quite a few commands, which can be hard to remember. 
There's still a few commands missing. I will add them in the next few days.

[NX] add Spec for Nx CLI

---

dangerfile.ts
dev/go.ts
specs/go.js

Feature
There is no completion spec for `go`
There will be one 🥳 

[GO] add completion spec

---

dev/git.ts
specs/git.js

Bug fix
Adding files which have characters which need to be escaped doesn't work with zsh
it works 🎉 

[GIT]: fix git add zsh issue

---

dev/ln.ts
specs/ln.js

Created a template for the ln command as I noticed there was not one yet

[LN]: add command

---

dev/adb.ts
specs/adb.js

Adds the spec for adb CLI
There isn't any spec for adb CLI
This PR adds the adb CLI

[ADB] Added adb spec

---

dev/git.ts

Feature
`git diff` doesn't suggest changed files for the arguments
It suggests all changes files
Closes #22

feat: add changed files generator

---

dev/pip.ts
dev/quickmail.ts

Feature: Support for [quick-mail](https://github.com/avikumar15/quick-mail-cli)
Closes #229 
This adds complete autocomplete tool for [quick-mail](https://github.com/avikumar15/quick-mail-cli)

Autocomplete support for quick-mail

---

dev/brew.ts

feature
Adds some missing commands and options.
1. Add `cleanup` command
2. Add `doctor` options
3. Add `leaves` options
1. cleanup code ->  https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/cleanup.rb#L22
2. doctor code -> https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/doctor.rb#L23
3. leaves code -> https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/leaves.rb#L18
1. cleanup
2. doctor
3. leaves

[BREW] Add commands, update options

---

dev/git.ts

Fixes a bug where git add adds a unnecessary \
git add \ [file added with fig]
git add [file added with fig]

fix-git-add

---

dev/more.ts

feature
Not found `more` command
Create `more` command

[MORE] Create more command

---

dev/amplify.ts

Feature
No completion spec for `amplify`
Add a completion spec for `amplify env`
[Amplify env docs](https://docs.amplify.aws/cli/teams/commands#team-workflows)

[AMPLIFY] Add amplify env spec

---

dev/volta.ts

Feature
No completion spec for `volta`
Add a completion spec for `volta`. 
- [Volta Docs](https://docs.volta.sh/reference/)
- Fulfills #240

feat: add volta completion spec

---

dev/node.ts
dev/python.ts
dev/python3.ts

Enhancement to suggestion priority
#295 
Priority is given to files (76) over folders.

[Node & Python] Prioritize file suggestions over folder suggestions

---

dev/zapier.ts

Add spec for the [Zapier CLI](https://github.com/zapier/zapier-platform). It was generated using [the oclif plugin](https://github.com/withfig/oclif-plugin).
We can probably make a fancier version that includes the args, but this is a good first step.

[ZAPIER] Add Zapier spec

---

dev/gatsby.ts

feat: add Gatsby CLI completion spec

---

dev/wrangler.ts

Feature: Support for the Cloudflare Workers `wrangler` CLI tool.
No `wrangler` support.
Adds completion spec for `wrangler`
* all commands.
* https://www.npmjs.com/package/cloudflare/wrangler
* https://github.com/cloudflare/wrangler#readme
* https://workers.cloudflare.com/

[Cloudflare][Wrangler] Add CLI completion spec

---

.eslintrc.js
dev/wp.ts

**NEW** autocomplete set for `wp-cli`
_N/A_
_N/A_
I've labelled this as a v0.1 release as it's not had much testing - yet!
My intention is to go through and double check all args & options over next few days.
In mean time I thought be good to get it out there for people to feedback on.
Also intend to add some generators for parts like activating/deactivating plugins with dynamic plugin list.
Cheers
James

wp cli autocomplete v0.3

---

dev/dotslash.ts

Prioritizes executable files
#220 No priority given to executable files.
Prioritizes executable files

[DOTSLASH] Prioritize executable files

---

dev/cargo.ts
dev/rustc.ts

Feature
#292 No support for rustc or cargo rustc
Adds support for rustc and cargo rustc

feat: add rustc + cargo rustc spec

---

dev/open.ts

Feature
Currently open doesn't have any options, but just suggests filepaths/directories.
Adds options!

[Open] Update Spec

---

dev/rg.ts

Feature
#103 
Adds basic Ripgrep completion spec

[Ripgrep] Add Completion Spec

---

dev/bosh.ts
dev/bundle.ts
dev/example/git_push.ts
dev/expo-cli.ts
dev/expo.ts
dev/gh.ts
dev/git.ts
dev/heroku.ts
dev/pip.ts
dev/psql.ts
dev/serverless.ts
dev/tmux.ts
dev/wp.ts
dev/yarn.ts
scripts/eslint-plugin-fig-linter/index.js
scripts/eslint-plugin-fig-linter/rules/no-duplicate-options-subcommands.js

Closes #323 
Failing tests are related as I have not yet updated all the specs. I'll wait for a review to do that.

chore(eslint): add no-duplicate-options-subcommands rule

---

dev/aws/cloudformation.ts

[AWS] [Cloudformation] add generators

---

dev/pm2.ts

Completion Spec: PM2 Spec
#144 

[PM2] Add Spec

---

dev/aws/lambda.ts

[AWS] [Lambda] Spec

---

dev/valet.ts

NEW laravel valet autocomplete
N/A
New autocomplete
Autocomplete spec for laravel (v8) valet (v2.15.x)

Laravel Valet autocomplete

---

dev/hasura.ts

[Hasura] Add Spec

---

dev/npx.ts
dev/prisma.ts
dev/yarn.ts

Add prisma autocomplete based on CLI docs reference 
https://www.prisma.io/docs/reference/api-reference/command-reference

Add prisma

---

dev/git.ts

Reverts withfig/autocomplete#349

Revert "[git] Add wildcard generator"

---

dev/git.ts

`switch` subcommand for `git`
#351

[git] switch subcommand

---

dev/npx.ts
dev/prettier.ts
dev/yarn.ts

Feature
Adds the `Prettier` Spec

[Prettier] Add Spec

---

dev/uniq.ts

[uniq] Add Spec

---

dev/pandoc.ts

[pandoc] Add Spec

---

dev/brew.ts

feature
brew uninstall only lists Formulae
brew uninstall lists Formulae + Casks, which we want.
- Addresses #371

feat: enhance brew uninstall

---

dev/npx.ts
dev/tsc.ts
dev/yarn.ts

Feature
Adds the `tsc` completion spec
https://www.typescriptlang.org/docs/handbook/compiler-options.html

[tsc] Add Spec

---

dev/git.ts

Feature Enhancement
#374 
Adds staged & unstated file suggestions to `git diff`

[git] [diff] Suggest staged & unstaged files

---

dev/git.ts

Enhancement
#369 Only local branches are available to checkout
Adds remote branches to the generator

[git] [checkout] Include Remote Branches

---

dev/fzf-tmux.ts
dev/fzf.ts

[fzf] Add spec

---

dev/googler.ts

Feature
Adds `googler` spec
https://github.com/jarun/googler#from-a-package-manager

[googler] Add Spec

---

dev/fd.ts

[fd] Add Spec

---

dev/aws/ecs.ts

[AWS] [ECS] start working on generators

---

dev/tmux.ts

feature
no shortcuts
added additional "shortcut" suggestion for a popular workflow

[tmux] added additional suggestion

---

dev/gcc.ts

feat: add gcc skeleton

---

dev/curl.ts

feature
only supports 3 options
now supports all options

[curl] added completion spec skeleton

---

dev/aws/eks.ts

[AWS] [EKS] add generators

---

dev/xcodebuild.ts
dev/xcrun.ts

[xcodebuild] Add Spec

---

dev/node.ts

feat: add `.mjs` files as node suggestions

---

dev/mask.ts
dev/php.ts
dev/serverless.ts
dev/wp.ts
schemas/fig.d.ts
scripts/create-example.sh

docs update
Some fig.io links are dead
Replaced with new links
I checked all fig.io links in the repo. There are no dead links left

feat: fix dead links

---

dev/gh.ts

Update the `gh` (GitHub's CLI tool) spec.

Update gh spec

---

dev/cmake.ts

Feature
#429 
Adds `cmake` spec

[cmake] Add Spec

---

dev/git.ts

Spec Update
Updates `git  bisect` subcommand

[git] Update Subcommand `bisect`

---

dev/gradle.ts

Feature
Adds `gradle` spec. (Although `./gradlew` doesn't work 😢)

[gradle] Add Spec

---

dev/yarn.ts

Update yarn spec
Add the `global` subcommands below
- `add` (with generator)
- `bin`
- `dir`
- `ls`
- `list`
- `remove` (with generator)
- `upgrade`
- `upgrade-interactive`

[yarn] Update yarn spec with "global" subcommands

---

dev/yarn.ts

https://github.com/withfig/autocomplete/issues/446

feat: add package suggestions to 'yarn upgrade'

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/typecheck.yml

Bug fix
Mutation of `package-lock.json` in ci workflows
Use `npm ci` to avoid `package-lock.json` mutations in ci workflows.

Use npm ci in actions

---

dev/fig.ts

feat: update suggestions for autocomplete.theme

---

dev/curl.ts
dev/ssh.ts
schemas/fig.d.ts

Add isRepeatable to option

---

dev/rm.ts
schemas/fig.d.ts

Edited descriptions for the references section

Reference revamp: Edited descriptions

---

dev/cot.ts

Adds Cot Editor Cli Support
No cot cli support
cot cli support
3rd contribution

cot editor cli add

---

dev/cargo.ts

Add test suggestions to `cargo test`. Currently `cargo test makes no suggestions`.

Cargo test listing

---

.github/ISSUE_TEMPLATE/main_issue_template.yml

To know if someone intend to work on the issue presented.

chore: update `main_issue_template.yml`

---

dev/npm.ts

- Add `devDependencies` and `optionalDependencies` as suggestions for `npm uninstall` command.
- Join `npm uninstall` aliases

feat: update `npm uninstall` generator

---

dev/youtube-dl.ts

feature
Spec is incomplete
All options have been added 

[youtube-dl] add all options

---

dev/z.ts

feat: add `z` spec

---

dev/eleventy.ts

Adds Eleventy Cli Support
No support
support
4th contribution

eleventy-cli

---

dev/fd.ts
dev/ps.ts
dev/ssh.ts

Add more is repeatable cases

---

dev/aws/ec2.ts
dev/conda.ts
dev/flutter.ts
dev/gcloud/composer.ts
dev/gcloud/debug.ts
dev/gcloud/iot.ts
dev/mysql.ts
dev/pandoc.ts
dev/pip.ts
dev/terraform.ts
dev/volta.ts

Links to @sullivan-sean 's #472

Add more isRepeatable cases

---

dev/omz.ts

This PR adds autocompletion support for OMZ (Oh My Zsh).

feat: add omz completion spec

---

dev/afplay.ts

Feature: adds specs for `afplay`

feat: add afplay completion spec

---

dev/afplay.ts
dev/cp.ts

First arg to copy is variadic. 
All options added per "man cp"

[cp] Finished spec

---

dev/npx.ts
dev/typeorm.ts
dev/yarn.ts

Adds autocomplete spec for [TypeORM](https://typeorm.io/#/) CLI.
- Adds `typeorm` to yarn `cli` array.

[TypeORM] Create TypeORM completion spec

---

schemas/fig.d.ts

Fix example in schema declaration file
Example does not compile
Example compiles

fix: Schema declaration example

---

dev/n.ts

Feature
No autocompletion for N (https://github.com/tj/n)
Full autocompletion for N
Includes dynamic suggestions for versions from `n lsr --all`

Add Spec for N

---

dev/hyper.ts

Feature : adds specs for `hyper`

feat: add hyper completion spec

---

dev/ag.ts

Add all the args from the `man ag` page.
This is my first time writing autocomplete specs so let me know if there's anything I should've done differently!
Fixes #529

Add spec for Ag (Silver Searcher)

---

dev/aws/configure.ts
dev/aws/sso.ts

Implements the only missing suggestion for AWS SSO
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso/index.html#cli-aws-sso

[aws] sso login

---

dev/diff.ts

feat: add `diff` spec

---

dev/fig.ts

Add new completions to Fig CLI
No support for `debug` subcommand

[FIG] add `debug` subcommand

---

dev/trash.ts

Add extra stuff to the trash cli spec stuff
No isDangerous or isOptional flags from some options, and fixes some descriptions
Has isDangerous or isOptional flags from some options, and descriptions are fine
6th contribution

trash-cli-fix

---

dev/sfdx.ts

Salesforce CLI spec generated using https://github.com/withfig/oclif-plugin
https://developer.salesforce.com/tools/sfdxcli

[sfdx] spec generated

---

dev/composer.ts

Feature
No autocompletion.
Two new commands which only appear in the presence of a `symfony.lock` file.
This is a composer plugin specific to the symfony framework (symfony flex).

Add autocompletion for composer recipes commands

---

dev/bazel.ts

Adding startup options to bazel
There is no options
Autocompletion for bazel's options

Adding startup options for bazel

---

dev/bazel.ts

Updated the description in bazel.ts making it more clear.
Changed using args instead of insertValue. 
The description is not clear. 

Bazel-update description and args

---

src/npm.ts

feat: add arg to `npm link`

---

src/subl.ts

This PR adds options to `subl`

feat(subl): add options

---

dev/serve.ts

feature: added autocompletion for serve
None.
Added autocompletion for serve in accordance with their help section
This is my first contribution to fig, and I'm by no means an expert in serve. So if you have any suggestions or something you would like to see different, please let me know.

feat(serve): add autocompletion spec

---

src/pdfunite.ts

Re submission of the PDFUnite spec.

pdfunite spec

---

src/npm.ts

[npm] add missing aliases

---

src/whois.ts

Removes non-existent options and adds all the other options
Incorrect options are suggested, and none of the actual options are
Because macOS, it's another BSD spec. Will need to be updated in the future.

feat(whois): add options

---

README.md
package.json

docs: update `README` and `package.json`

---

src/brew.ts

Fix
Services generator isn't working properly
Services generator is now working as expected

fix(brew): Services generator

---

src/wc.ts

Feature
No spec for `wc`
Add a spec for `wc`

feat: Add `wc` spec

---

src/npm.ts

feat(`npm`): suggest global deps if global flag is specified

---

src/amplify.ts

Full spec for amplify CLI autocomplete support
Only amplify env is supported
All amplify commands are supported

added all amplify commands to spec

---

src/truffle.ts

Add auto completion for truffle.
No current behavior.
Show completion options for the truffle suite.
[Truffle Commands](https://www.trufflesuite.com/docs/truffle/reference/truffle-commands)

feat: add truffle completion spec

---

src/create-nx-workspace.ts

feature
No autocomplete for `create-nx-workspace`
Autocomplete for `create-nx-workspace`

feat(nx): Add create-nx-workspace CLI autocomplete

---

src/vercel.ts

Added completion for for vercel's alias, link, billing
Missing completion specs for alias, link, billing. See #694 
Completion for vercel's alias, link, billing
none

feat(vercel): Added completion for vercel's alias, link, billing

---

src/ssh.ts

Feature/enhancement
Fetches hosts only from `~/.ssh/config`
Now also fetches hosts from `~/.ssh/known_hosts`
Also changed the description from `Ssh host` to `SSH host`

SSH enhancement

---

src/doppler.ts

This adds specs for `doppler` as requested on issue #704

feat: doppler spec

---

src/ni.ts
src/nr.ts
src/nrm.ts
src/nu.ts

Feature
No specs for ni
Add specs for ni (ni, nr, nu, nrm)
https://github.com/antfu/ni

feat(ni): add ni specs

---

src/remotion.ts

Bug fix
wrong name
correct name

Fix typo in Remotion autocomplete

---

src/fig.ts

This adds a versioned spec for the new CLI which also supports the legacy CLI.

feat(fig): add spec for new CLI

---

src/fig.ts

Reverts withfig/autocomplete#719
Seems like there is an issue with versioned specs. I am going to revert this for the time being

Revert "feat(fig): add spec for new CLI"

---

src/vapor.ts

Add completion spec for [Vapor](https://vapor.codes/).
No completion spec for Vapor.
Added completion spec for [Vapor](https://vapor.codes/).

feat: add vapor completion spec.

---

src/dog.ts

This adds specs for `dog` as requested on issue #702

feat: dog spec

---

src/brew.ts

brew cleanup args are optional

---

src/npm.ts

Fix: Typo in description (´npm run´)

Fix: Typo in description

---

src/git.ts

feature
`ls-remote` is missing in spec
`ls-remote` is now in spec

added ls-remote to git spec

---

src/okteto.ts

New feature
It adds a spec for [okteto](https://github.com/okteto/okteto)
We generated the spec using the cobra integration for go, and then copied the src file to the folder.

add okteto spec

---

src/jupyter.ts

Feature: Add completion spec for Jupyter

feat: add jupyter completion spec

---

src/create-react-app.ts

Feature: Add `create-react-app` completion spec

feat: add create-react-app completion spec

---

src/deta.ts

Creating the specs for the [Deta CLI](https://www.deta.sh/). The references follow the [Deta CLI Docs](https://docs.deta.sh/docs/cli/commands) on the latest version [v1.3.0-deta](https://docs.deta.sh/docs/cli/releases#v130-beta). The descriptions of the commands are also extracted from the docs. 
Also pinging the @deta folks here in case of review @abdelhai @aavshr @rohanshiva @rabingaire @xeust

feat: add deta completion spec

---

src/git.ts

Improve `git merge`
Only suggests local branches
Also suggest remote branches
Resolves https://github.com/withfig/autocomplete/issues/737

[git] allow merge with remote branches also

---

src/mvn.ts

New completion spec
Non-existent
Existent
Resolves https://github.com/withfig/autocomplete/issues/605

feat: add mvn (Maven) completion spec

---

src/redwood.ts

feature
We don't give suggestion for script 
We give suggestion for script when running `yarn rw exec "name"`
https://redwoodjs.com/docs/cli-commands.html#exec

Feat: Add suggestion for script in Redwood project

---

src/go.ts

Feature.
Doesn't have any suggestions.
Suggests filepaths.

feat: suggest filepaths for go run/build/etc

---

src/swc.ts

This PR adds support for [SWC](https://swc.rs/docs/usage/cli).

feat: added support for SWC

---

src/ssh.ts

Bug fix
`known_hosts` generator produces duplicates.
All suggestions from `known_hosts` are unique
Resolves https://github.com/withfig/autocomplete/issues/748

[ssh] fix duplicates issue with known_hosts generator

---

src/@withfig/autocomplete-tools.ts

This should be merged once I will have created the preset in the autocomplete-tools repo

feat(autocomplete-tools): update `merge` suggestions

---

src/dbt.ts

Adding suggestions for CLI options with enumerated arg values. Adding build and parse commands.  Adding new flags and arguments to various commands. 
Feature expansion.
Limited DBT CLI support.
Expanded support for DBT CLI.

Feature - expand DBT support. 

---

src/docker-compose.ts
src/docker/compose-up.ts

Fixes issues with `docker-compose` generators.

Improve docker-compose completions

---

src/npm.ts

Fixed typo.
```
overide -> override
```

chore: typo in npm.ts

---

src/pulumi.ts

Feature add [pulumi-cli](https://www.pulumi.com/docs/reference/cli/)
No autocomplete for `pulumi-cli`
Add autocomplete to `pulumi-cli`
Resolves #669 
Spec has been added manually from the [official documentation](https://www.pulumi.com/docs/reference/cli/)

feat: add `pulumi cli` to autocomplete 

---

src/omz.ts

Feature
Command not available.
Add the command `version`.
https://github.com/ohmyzsh/ohmyzsh/commit/f0f792fa6b207bc72453ae55011b6b44f678fb78

feat: add version command to omz spec

---

src/circleci.ts

feature: add circleci spec
Normal
New autocomplete suggestions for the CircleCI CLI
N/A

feat: add CircleCI completion spec

---

src/fig/fig@1.0.52.ts

feat(fig): add `wrapped` subcommand

---

src/node.ts

node ace: add AdonisJs mailer command

---

src/keytool.ts

Feature.
Fig doesn't have support for `keytool` command line tool.
Fig has comprehensive completion for `keytool`.

Keytool support

---

src/yarn.ts

Feature
There's limited support for the `yarn upgrade` command when run locally.
Comprehensive `yarn upgrade` command support with all the options.

Enhance `yarn upgrade` local support

---

src/yarn.ts

Feature
Fig doesn't have good support for the `yarn why` command
Fig has comprehensive support for the `yarn why` command.

Add `yarn why` support

---

src/ignite-cli.ts
src/npx.ts

Feature
Fig doesn't have completion support for [Ignite](https://github.com/infinitered/ignite).
Fig has comprehensive support for Ignite.

Ignite Support

---

src/deno.ts

feat(deno): update spec to 1.17

---

src/docker.ts

feat(docker): enhance docker run completion

---

package.json

Feature
No YAML parsing is available.
autocompletes can support YAML parsing.
Resolves #799

feat: add yaml to runtime dependencies

---

src/git.ts
src/pre-commit.ts

feature - new spec
no spec exists
new completions!
Popular CLI tool: https://pre-commit.com/
I left a couple of notes inline to help improve this in the future.

feat: add autocomplete for pre-commit

---

src/git.ts

Sort git branches/tags generators by commit date, currently they are alphanumerically sorted.

feat(git): sort git branches/tags by commit date

---

README.md

withfig/fig#743 has been merged, now we can update the banner here too!

Add dark mode banner

---

src/yarn.ts

Feature
Having `create-*` CLIs hardcoded in an array that Fig searches in.
Search for `create-*` term using npm API and load CLI spec dynamically if exists.

feat: dynamically complete `yarn create` CLIs

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/update-codeowners.yml

chore(ci): add update codeowners workflow

---

src/pass.ts

New Feature: Added [pass](https://www.passwordstore.org/) auto completion.
Man page for pass - https://git.zx2c4.com/password-store/about/

feat: add `pass` completion spec

---

src/mackup.ts

Popular macOS backup/restore tool
Feature
No spec for tool
Spec works for tool!
Refs: https://github.com/lra/mackup

feat: new spec for `mackup` tool

---

src/swift.ts

> **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
> **What is the current behavior? (You can also link to an open issue here)**
> **What is the new behavior (if this is a feature change)?**
> **Additional info:**

Add `swift` spec

---

src/vapor.ts

update spec.
spec needs update.
updated vapor spec with more information.
spec previously added by myself [feat: add vapor completion spec. #721](https://github.com/withfig/autocomplete/pull/721/files)

feat(vapor): enhance vapor completion

---

src/gh.ts

Add missing commands to the `gh` specs (alias)

feat: improvement of the `gh` specs with new alias commands

---

dev/doctl.ts

Completion for the digital ocean CLI :: `doctl`

feat: add `doctl` spec

---

generate-index.js
package.json

Instead of becoming crazy trying to fix some problems with modules just use vanilla node along with an old good js file😄

fix: build script

---

src/grep.ts

fix(grep): add `isRepeatable` to option

---

src/eb.ts

Feat
It doesn't support all `eb` subcommands from AWS
Now `ssh` subcommand and all options are supported
I will continue working adding the `eb` specs

feat(eb): add ssh subcommand

---

package.json

fix: correct `copy` scripts destination paths

---

src/opa.ts

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
feature
[opa CLI](https://github.com/open-policy-agent/opa) auto-completion
We've followed the official page [here](https://fig.io/docs/guides/autocomplete-for-teams/cobra).
cc: @srenatus @anderseknert

feat(opa): add opa autocompletion

---

src/nest.ts

Feature
No autocomplete support for nest
Adds autocomplete for the [Nest Cli](https://docs.nestjs.com/cli/overview)

Add Nest Spec 

---

src/fig/shared.ts

feat(fig): update built in themes

---

src/npm.ts

feat(npm): package version suggestions

---

src/sqlite3.ts

feature
no support for sqlite3
added support for sqlite3

`sqlite3` support

---

src/fig/fig@latest.ts

feat(fig): add suggestions to `fig debug build`

---

src/okteto.ts

This updates the okteto completion script to match the new commands released on v1.15

Update the okteto autocomplete spec to v1.15

---

src/aws/s3.ts

fix(aws): s3 ls argument should be optional

---

src/cargo.ts

New subcommands: tree
New supported plugins: fmt, clippy, flamegraph, audit

feat(cargo): Add tree and cargo plugins

---

src/gh.ts

gh: Enhance pr create --b

---

src/ping.ts

feat: add `ping` spec

---

src/vim.ts

Add vim command line options 
No command line options
Command line options

Add support for vim command line options, for #858

---

src/ffmpeg.ts

Add attribution for ffmpeg spec

---

src/tokei.ts

This PR adds a spec for [tokei](https://github.com/XAMPPRocky/tokei).

feat(tokei): Add tokei spec

---

src/open.ts

Bug fix
`open`'s spec isn't complete. #872 
`open`'s spec is complete.

Completes `open` spec

---

src/spotify.ts

Feature
`spotify` commands are currently not-supported
Autocompletion support for `spotify` commands
Link of [shpotify](https://github.com/hnarayanan/shpotify)

feat: add shpotify spec

---

src/black.ts

feature
No autocomplete for Black
Add autocomplete spec for [Black](https://github.com/psf/black) code formatter

feat(black): add completion spec

---

.all-contributorsrc
src/vr.ts

feature
added a completion spec for [Velociraptor](https://velociraptor.run), the npm-style script runner for Deno

feat(velociraptor): add completion spec

---

src/rushx.ts

feature
add rushx spec. see https://rushjs.io/pages/developer/everyday_commands/#rushx

feat: add `rushx` spec

---

src/kill.ts

feat(kill): add process names, fix `-s` generator

---

package.json
src/rush.ts

add project suggestion support for rush spec

feat(rush): add project suggestion

---

src/amplify.ts

add new sub commands to amplify cli

feat(amplify): add new subcommands

---

src/gh.ts

Add completion alias when you type `gh` in your terminal (like git does)

feat(gh): alias autocompletion

---

src/atlas.ts

Ref https://github.com/mongodb/mongocli/pull/995

feat: add `atlas` spec

---

src/pulumi.ts

fix(palumi): move options under the correct prop name

---

src/date.ts
src/micro.ts

feature
Add completion spec for [micro](https://github.com/zyedidia/micro) editor.

feat: add `micro` completion spec

---

src/tar.ts

Spec update
The spec is incomplete: Closes #962
**Additional Info**
There aren't currently any generators or any 'clusters' (e.g. tar **cfv** a.tar /etc) but I could ad them if wanted.

feat(tar): improve spec

---

src/bat.ts
src/date.ts

Implement bat command spect
bat command could auto-complete now
The feature before is just a copy of cat that introduce the command briefly. 
Now, the whole auto-complete is worked.

feat: implement bat spec

---

src/id.ts

**What kind of change does this PR introduce? New completion spec for id
This is my first spec, and first pull request.  I'm a beginner, so the code may not be correct.  It did pass the npm test and lint:fix.

feat: add `id` spec

---

src/brew.ts

Improves `brew upgrade` command
See Issue: closes https://github.com/withfig/autocomplete/issues/1003
- Suggests outdated formula
- Added options
- Fixed documentation
- Fixes some options

feat(brew): improvements for "brew upgrade"

---

src/mas.ts

Feature add autocomplete for [mas-cli](https://github.com/mas-cli/mas)
Currently there is not autocomplete for mas
Added autocomplete for mas
none

feat: add `mas` completion spec

---

src/pip3.ts

feat: add pip3 as import from pip

---

src/fig/fig@latest.ts
src/fig/shared.ts

This will probably be receive changes before the CLI is on prod. Once the rust CLI is in production, further changes will automatically create the update-PR. CI workflow isn't done yet but will be.

chore(fig): update spec for v1.0.56

---

src/npm.ts

Improve completion spec of `npm`
Several commands are incorrectly grouped. Several options are missing
Partially fixes issue: https://github.com/withfig/autocomplete/issues/983
Improves multiple subcommands
NOTE: Though this improves the whole npm spec by adding options to certain subcommands and by grouping aliased subcommands together, this is in no way exhaustive and further improvements would be needed
Follow up of: https://github.com/withfig/autocomplete/pull/1001 and https://github.com/withfig/autocomplete/pull/1019

feat(npm): improvements

---

src/publish.ts

CLI for https://github.com/JohnSundell/Publish

feat: add `publish` spec

---

src/deno.ts

fix(deno): add `isScript` to `deno run` arg

---

src/create-web3-frontend.ts

Adds an autocomplete spec for [create-web3-frontend](https://github.com/dhaiwat10/create-web3-frontend)

feat: add `create-web3-frontend` autocomplete spec

---

src/npx.ts
src/vite.ts
src/yarn.ts

feat: add `vite` cli spec

---

src/node.ts

Adding spec of node: `--preserve-symlinks`

feat: update node spec

---

src/git-flow.ts

Feature
`git-flow` commands are currently not-supported
Autocompletion support for `git-flow` commands

feat: add basic spec for git-flow

---

src/drush.ts

Feature
Missing support for drush autocomplete.
Autocomplete support for drush.

feat: add drush spec

---

src/open.ts

`open` completion spec description update.
The description only describes opening files, even though [(as seen on @fig's Twitter)](https://twitter.com/fig/status/1507028223879614466) the `open` command can also open applications and URLs.

fix(open): update completion spec description

---

src/vale.ts

Feature
Missing support for [Vale](https://github.com/errata-ai/vale) autocomplete.
Autocomplete support for Vale.

feat: add vale completion spec

---

src/robot.ts

Feature: added autocomplete spec for [Robot Framework](https://robotframework.org)
Currently there isn't autocomplete Robot Framework

feat: add `robot` spec

---

package.json
src/deno.ts
src/deno/generators.ts
src/git.ts
src/npm.ts

This is in preparation for switching to an automatically generated spec 🎉 
Must be merged after #1048 (this also adds swr to deno tasks generator)

refactor(deno): move generators to another file

---

package.json
src/git.ts
src/npm.ts
src/vr.ts
src/yarn.ts

This can only be merged once SWR is in prod
Let me know if there are other generators where this would be appropriate!

feat: add stale-while-revalidate cache to appropriate generators

---

src/kubectl.ts

feature
#1059 
We will have more commonly used verbs is suggestions，such as "*", "get", "delete", "list", "create", "update", "patch", "watch".

feat:  supplement [kubectl] suggestions

---

src/kubectl.ts

@mschrage it should be happy now!
This was one of those weird times when prettier in pre-commit and prettier in vscode have very different opinions

style: appease linter

---

src/shopify.ts

**Feature** : this PR introduces autocompletion for the [shopify-cli](https://shopify.dev/apps/tools/cli/core-commands).

feat: add `shopify-cli` spec

---

src/oh-my-posh.ts

feat: add oh-my-posh

---

src/robot.ts

Fix `robot` spec description

---

src/tfsec.ts

This PR adds the spec for tfsec and fixes #1098 
-
-

feat: add tfsec spec

---

src/trivy.ts

This PR adds trivy spec to fig and fixes #1101 
-
-

feat: add trivy spec

---

src/httpy.ts

feat: add httpy completion spec

---

src/rsync.ts

Feature.
`rsync` is not available. Closes #510 .
Support for `rsync`.

feat: add rsync spec

---

src/helm.ts

This PR fixes #1066 
No `helm` support
Add `helm` support
-

feat: add helm spec

---

src/wd.ts

Feature - new spec
This is a spec for the [wd plugin](https://github.com/mfaerevaag/wd) by [mfaerevaag](https://github.com/mfaerevaag)

feat(wd): add `wd` plugin spec

---

src/hx.ts

https://github.com/helix-editor/helix
I'm actually really loving this editor!

feat: add `hx` spec

---

src/fig/fig@latest.ts
src/fig/shared.ts

feat(fig): add generators for `fig plugins`

---

src/deno.ts

feat(deno): add hidden `-` suggestion

---

src/vimr.ts

Autocomplete added for https://github.com/qvacua/vimr
N/A
N/A
N/A

feat: add `vimr` completion

---

src/robot.ts

Bug fix
Generator for test cases names doesn't work in some situations
Generator for test cases names works

fix(robot): test cases generator regex

---

src/docker.ts

Fixes #1117 
No sbom spec
`docker sbom` support

feat: add Docker sbom spec

---

src/dtm.ts

Feature
`dtm` command are not currently supported
Autocompletion support for `dtm`
`dtm` project found [here](https://github.com/devstream-io/devstream)

feat: add `dtm` spec

---

README.md

subcomands -> subcommands

---

package.json
src/fig.ts
src/fig/fig@latest.ts
src/fig/index.ts

Reverts withfig/autocomplete#1108

Revert "feat(fig): use diff-versioned specs"

---

src/noglob.ts

feat: add `noglob` precommand modifier

---

src/-.ts
src/..ts
src/command.ts
src/do.ts
src/echo.ts
src/elif.ts
src/else.ts
src/exec.ts
src/for.ts
src/if.ts
src/noglob.ts
src/repeat.ts
src/then.ts
src/until.ts
src/whence.ts
src/where.ts
src/which.ts
src/while.ts

Fixes https://github.com/withfig/fig/issues/1317
Also adds support for basic things like `if` (and `then`/`elif`/`else`), `for`, etc.

feat: add shell syntax "commands"

---

src/cloudflared.ts

Feature.
Closes #1091, missing spec of cloudflared.
Support for cloudflared CLI

feat: add cloudflared spec

---

src/nuxi.ts

fix(nuxi): Typo in Args name

---

README.md

- docs update
- N/A
- N/A
- None

docs: correct install command

---

src/kitty.ts

feat(kitty): add spec

---

src/brew.ts
src/valet.ts

Feature
Spec does not exist for the untap subcommand
Adds a spec for `brew`'s `untap` subcommand
Fixes #1152

Brew untap spec

---

src/arch.ts

Fix description in arch for -64 flag

---

src/fig/1.0.0.ts

Fix typo in Fig 1.0.0

---

src/steadybit.ts

New autocompletion spec for the [steadybit CLI](https://github.com/steadybit/cli)
No autocompletion :trollface: 
Auto completion! ❤️ 

feat(steadybit): add spec

---

src/osascript.ts

docs update
Closes #939 
Add spec
Man page: https://keith.github.io/xcode-man-pages/osascript.1.html

feat: add osascript spec

---

src/hb-service.ts

docs update
add spec
add spec
About hb-service: https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command
Some of commands and options does not have official description. I remained them blank.

feat: add `hb-service` spec

---

src/fig/1.0.0.ts

feat(fig): update spec

---

src/kubectl.ts

feat(kubectl): add cache to generators

---

src/pmset.ts

Adds spec
The spec doesn't exist
The spec exists
Closes #1181

feat: add spec for `pmset`

---

src/rollup.ts

Feature
#1188 
Adds rollup spec

feat: add `rollup` spec

---

src/cargo.ts

feat(cargo): add `outdated` subcommand

---

src/yarn.ts

fix(yarn): upgrade subcommand argument is optional

---

src/mosh.ts

feature, new completion spec for mosh.
missing completion for mosh, mobile shell
new completion spec

feat: add mosh completion spec

---

src/croc.ts

Feature, adding spec for croc, the command line tool for sending files and folders.
No current spec for croc.
Adding spec for the croc command.

feat: add croc spec

---

src/vela.ts

Signed-off-by: tianshuai 
kubevela is A Highly Extensible Platform Engine based on Kubernetes and Open Application Model.
Feature to support vela cli
support vela (cli for kubevela) autocomplete
vela cli info: https://kubevela.net/docs/cli/vela

feat: add kubevela cli spec

---

src/nc.ts

New completion
There is no completion for `nc` currently
There will be completion for `nc`
`man nc`

feat(nc): add completion

---

src/ansible-config.ts

New completion
There is no completion for `ansible-config` currently
There will be completion for `ansible-config`
`man ansible-config`

feat(ansible-config): add completion

---

src/who.ts

New completion
There is no completion for `who` currently
There will be completion for `who`
`man who`

feat(who): add completion

---

package.json
src/nylas.ts

Nylas CLI Autocomplete
Autocompletion for the Nylas CLI.
There's no autocompletion for the Nylas CLI.
You can finally use autocompletion for the Nylas CLI https://developer.nylas.com/docs/developer-tools/cli/getting-started/#prerequisites

feat: add support for Nylas CLI

---

src/fold.ts

New completion
There is no completion for `fold`
There will be completion for `fold`
`man fold`

feat(fold): add completion

---

src/od.ts

New completion
There is no completion for `od`
There will be completion for `od`
`man od`

feat(od): add completion

---

src/rg.ts

typo(rg): fix typo

---

src/sftp.ts

New completion
There is no completion for `sftp`
There will be completion for `sftp`
`man sftp`

feat(sftp): add completion

---

src/fmt.ts

New completion
There is no completion for `fmt`
There will be completion for `fmt`
`man fmt`

feat(fmt): add completion

---

src/ansible-doc.ts

New completion
There is no completion for `ansible-doc` currently
There will be completion for `ansible-doc`
`man ansible-doc`

feat(ansible-doc): add completion

---

src/screen.ts

New completion
There is no completion for `screen`
There will be completion for `screen`
`man screen`

feat(screen): add completion

---

src/ansible-galaxy.ts

New completion
There is no `ansible-galaxy` completion
There will be `ansible-galaxy` completion
`ansible-galaxy -h`

feat(ansible-galaxy): add completion

---

src/terragrunt.ts

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)** feature
**What is the new behavior (if this is a feature change)?** add terragrunt spec
[https://terragrunt.gruntwork.io/docs/reference/cli-options/](https://terragrunt.gruntwork.io/docs/reference/cli-options/)

feat: add terragrunt spec

---

src/vault.ts

New completion (opening this as a Draft to prevent duplication of effort)
There is no completion for `vault`
There will be completion for `vault`
`vault -h`

feat(vault): add completion

---

src/op.ts

Also adds a description. Love a PR that removes thousands of lines, Vim macros are godlike ⚡

refactor(op): remove repeated options

---

src/install.ts

New completion
There is no completion for `install`
There will be completion for `install`
`man install`

feat(install): add completion

---

src/npm.ts

fix(npm,yarn,pnpm): cache scripts by directory

---

src/trunk.ts

Feature
No completion spec for `trunk`
Creates completion spec for `trunk`
[trunk website](https://trunk.io/products/check)

feat: create `trunk` completion spec

---

src/pathchk.ts

New completion
There is no completion for `pathchk`
There will be completion for `pathchk`
`man pathchk`

feat(`pathchk`): add completion

---

src/tee.ts

New completion
There is no completion for `tee`
There will be completion for `tee`
`man tee`

feat(tee): add completion

---

src/truncate.ts

New completion
There is no completion for `truncate`
There will be completion for `truncate`
`man truncate`

feat(truncate): add completion

---

src/aftman.ts

New spec for [aftman](https://github.com/LPGhatguy/aftman)
Aftman is a toolchain manager. It enables installing project-specific command line tools and switching between them seamlessly.

feat(aftman): add spec

---

src/mkfifo.ts

New completion
There is no completion for `mkfifo`
There will be completion for `mkfifo`
`man mkfifo`

feat(mkfifo): add completion

---

src/shred.ts

New completion
There is no completion for `shred`
There will be completion for `shred`
`man shred`

feat(shred): add completion

---

src/mknod.ts

New completion
There is no completion for `mknod`
There will be completion for `mknod`
`man mknod`

feat(mknod): add completion

---

src/datree.ts

- feature:
- Add `datree`
- Closes #1302 
- `datree` CLI completion

feat(`datree`): add completion

---

src/nuxi.ts

- **Added**: Icon Path / Description to the main command. 
- **Added**: Emoji's to subcommands to make it look prettier.
- **Added**: more sub-commands to be updated with docs.
- `test` - command [here](https://github.com/nuxt/framework/blob/main/packages/nuxi/src/commands/test.ts)
- `usage` - command [here](https://github.com/nuxt/framework/blob/main/packages/nuxi/src/commands/usage.ts)
- **Added**: `templates: 'folders'` to **rootDir**  to auto complete directory name. 
- **Fixed** : Some english grammar that was misspelled.
It has the basic functionality and was out of date for some commands.
**What is the new behavior (if this …

feat(nuxi): improve style and add more commands

---

src/molecule.ts

New feature to support completion for https://molecule.readthedocs.io/en/latest/

feat: add molecule completion spec

---

src/hostname.ts

New completion
There is no completion for `hostname`
There will be completion for `hostname`
`man hostname`

feat(`hostname`): add completion

---

src/heroku.ts

feat: add caching when loading heroku apps

---

src/ng.ts

Bug fix
There is no completion for ng.ts
In the angular version 14 its moved the version checking 
check https://github.com/angular/angular-cli/blob/8da926966e9f414ceecf60b89acd475ce1b55fc5/packages/angular/cli/src/commands/version/cli.ts

Update For ng 14

---

src/chown.ts
src/st2.ts

New completion
There is no completion for `st2`
There will be completion for `st2`
[st2client](https://pypi.org/project/st2client/)

feat(`st2`): add completion

---

src/bun.ts
src/npm.ts

Bun is launching very soon! This is correct as of 0.0.83 but 0.1.0 may be slightly different.

feat: add `bun`

---

src/php.ts
src/php/bin-console.ts

Feature
Adding completions for Symfony bin/console

feat(php): add bin/console (Symfony) command

---

src/create-t3-app.ts
src/create-t3-app@latest.ts
src/npx.ts

Feature add [create-t3-app](https://create.t3.gg/)

feat: add `create-t3-app` spec

---

src/fig/1.0.0.ts
src/fig/shared.ts
src/tsh.ts

feat(fig): add fig-team cli generators

---

src/eb.ts

feat(eb): add env name generator

---

src/cargo.ts

Adds the `cargo add` subcommand and `--timings` flag to multiple sub commands

feat(cargo): Add `add` subcommand and `--timings`

---

src/pgcli.ts

Feature
New autocomplete
Refs: https://github.com/dbcli/pgcli

feat: add pgcli command

---

src/create-t3-app.ts

feat: update create-t3-app spec

---

src/git.ts

This is a fairly common complaint, finally fixing it

feat(git): don't insert leading `remotes/.../` in branch name

---

src/npm.ts
src/yarn.ts

fix(npm): suggest flags after script name

---

src/java.ts

Feature about `Java` basic cmd.

feat: add java spec

---

src/bun.ts
src/cargo.ts
src/fig/1.0.0.ts
src/fig/shared.ts
src/git.ts
src/npm.ts
src/nr.ts
src/nrm.ts
src/pnpm.ts
src/rushx.ts
src/trex.ts
src/ts-node.ts
src/yarn.ts

feat: add more `filterStrategy`

---

src/hop.ts

Adding completion spec for Hop's CLI  - Interact with Hop in your terminal

feat: add hop

---

src/prisma.ts

Update to `prisma` CLI commands
I work at Prisma and this is our official docs https://www.prisma.io/docs/reference/api-reference/command-reference

prisma: update and add new commands

---

src/zellij.ts

This was generated by clap_complete_fig but I've gone over it to make sure everything is as expected

feat: add `zellij`

---

src/dtm.ts

feat(dtm): update spec

---

src/conda.ts

fix: longer timeout for conda env list

---

src/mamba.ts

[Mamba](https://github.com/mamba-org/mamba) is a faster alternative for conda written in C++.
New Spec for `mamba` 
Most of it is taken from the spec for `conda`

feat: add `mamba` spec

---

src/docker-compose.ts

~~This seems like a good opportunity for version based specs, will implement this before merge~~

feat(docker-compose): update to v2

---

src/fig/1.0.0.ts
src/fig/shared.ts

Note: requires develop version of fig_cli

feat: add generators for fig ssh

---

src/pipenv.ts

fix(pipenv): add extended arg support

---

src/streamlit.ts

Feature
No autocompletion for [Streamlit](https://streamlit.io/) 😢
Added autocompletion for Streamlit 🎈, with all commands and options mentioned in the help message: 
1. Great tool!! Just discovered 2h ago and using fig + creating a spec was super smooth.
2. I'm a PM at Streamlit, so happy to maintain this if we update something on our side. 
3. If you want to know more about Streamlit, feel free to reach out 😉

feat: add `streamlit` spec

---

src/copyfile.ts
src/copypath.ts

feat: add `copyfile` and `copypath`

---

src/gibo.ts

Adds completions for [gibo](https://github.com/simonwhitaker/gibo)
n/a
fig supports gibo

feat: add gibo completion spec

---

src/fig/1.0.0.ts

feat(fig): update spec for 1.4.10

---

src/fig/1.0.0.ts
src/fig/shared.ts

feat(fig): add user switch generator

---

src/ibus.ts
src/ldd.ts

feat: add `ibus` and `ldd` completions

---

src/make.ts

feat(make): support targets with variables

---

src/xdg-mime.ts
src/xdg-open.ts

feat: add `xdg-mime` and `xdg-open`

---

src/cf.ts

Adding spec for `cf` cloudfoundry-cli

feat: add cf

---

src/pip.ts

fix(pip): make install variadic

---

src/wezterm.ts

feat: add `wezterm` spec

---

src/apt.ts

potentially closes #1397 
big thanks to Grant and Robert for helping me get generators figured out :)

feat: add `apt`

---

src/minectl.ts

Adds support for `minectl`, closes #1434

feat: add minectl cli spec

---

src/mount.ts

feat: add `mount` spec

---

src/helm.ts

Update of the helm cli using the autocomplete-tools for cobra
-
Update of the helm cli using the autocomplete-tools for cobra

feat: update helm spec with autocomplete-tools for cobra

---

src/mkinitcpio.ts

Feature
Autocompletion for mkinitcpio is currently not available. Closes https://github.com/withfig/autocomplete/issues/1409
Adds autocompletion for mkinitcpio

feat: add `mkinitcpio` spec

---

src/pipx.ts

Add spec for [pipx](https://github.com/pypa/pipx)

feat: add pipx

---

src/man.ts

Reused some of the logic I wrote for apt which has a similar situation! Tens of thousands of lines of output
The current man generator is incorrect and sometimes misses suggestions, this one never does

feat(man): correct generator

---

src/tree.ts

feature
n/a
Adds a new spec for [tree](http://mama.indstate.edu/users/ice/tree/)
n/a

feat: add tree completion spec

---

src/cd.ts

feat(cd): use fuzzy search

---

src/deno.ts

Can't update automatically because there's a fair amount that has to be cleaned up manually in this spec, but _wow_ it is much easier to scan the Fig spec diff than diff the deno CLI's source code!! Using the generated spec helped so much.

feat(deno): update to 1.25.0

---

src/sanity.ts

Feature: [Sanity.io](https://www.sanity.io) completion specs.
Currently the `sanity` CLI features no completion spec.
The `sanity` CLI offers completions.

feat: add `sanity` completion spec

---

src/pocketbase.ts

This PR will add a completion spec for the PocketBase backend [https://pocketbase.io](https://pocketbase.io)
N/A
All commands and subcommands are supported now 🙂

feat: add pocketbase completion spec

---

src/osqueryi.ts

CLI for https://github.com/osquery/osquery
This took about 5 mins total because [Helix](https://github.com/helix-editor/helix) is _amazing_ for creating specs out of help text

feat: add `osqueryi`

---

src/cargo.ts

Add `udeps`, `deny`, `bloat`, `sort`, and `fuzz`

feat(cargo): add cargo plugins

---

src/@magnolia/cli.ts
src/mgnl.ts
src/npm.ts
src/npx.ts

feature
n/a
Adds a new spec for [mgnl](https://docs.magnolia-cms.com/magnolia-cli/4.x/magnolia-cli.html)
n/a

feat: add mgnl completion spec

---

src/k9s.ts

feature
N/A
Add `k9s` completion spec ([issue](https://github.com/withfig/autocomplete/issues/1454))
N/A

feat: add k9s completion spec

---

src/git.ts

Used a little script to generate this from [git/git](https://github.com/git/git)'s Documentation/config folder, then cleaned up manually

feat(git): add new git settings

---

src/man.ts

feat(man): improve generator perf/caching

---

src/scc.ts

feat(scc): use keyValueList

---

src/mailsy.ts

Adding completion spec for [Mailsy](https://github.com/balliAsghar/mailsy) - ⚡️ Quickly generate a disposable email straight from terminal.

feat: add mailsy

---

src/gh.ts

This was failing before due to some very strange issues, `null is not an object` uhh yeah no it's not that's a string
No clue why it was failing, but it's fixed with this rewrite

fix(gh): rewrite listPR generator

---

src/nextflow.ts

It's a feature. Improve autocomplete with generators.
The `run` command will only suggest downloaded projects, but not local files ending in `.nf` in the current directory.
Suggest also local files ending in `.nf` in the current directory.

feat(nextflow): Improve nextflow spec

---

src/gem.ts

feature
N/A
Add `gem` completion spec (https://github.com/withfig/autocomplete/issues/1478)
Add the `install` subcommand first.

feat: add gem completion spec

---

src/minectl.ts

feat(minectl): update spec

---

src/tmutil.ts

this was surprisingly difficult

feat: add tmutil

---

src/stow.ts

feature
done
this commands only has options

feat: add stow spec

---

src/tsuru.ts

feat: add tsuru-cli

---

src/dotenv-vault.ts

Adding completion spec for [dotenv-vault](https://github.com/dotenv-org/dotenv-vault)
I and others enjoy Fig but have been missing autocompletion for dotenv-vault. Excited to get it into Fig's excellent autocompletion system!

feat: add dotenv-vault

---

src/fig/shared.ts

feat: add workflow icons

---

src/fig/shared.ts

feat(fig): Remove trailing space from workflow insertion

---

src/supabase.ts

Closes #713, closes https://github.com/withfig/autocomplete/issues/1556
This spec is autogenerated using cobra.
Thanks @fedeci for pointing out the guide on Fig! 
P.S. please add hacktoberfest label 🐱 
**Screenshots**

feat: add supabase completion spec

---

src/airflow.ts

Feature: add airflow auto completion CLI
Closes https://github.com/withfig/autocomplete/issues/1343
add airflow CLI

feat: add airflow

---

src/maigret.ts

Adds autocomplete for [maigret](https://github.com/soxoj/maigret)
Autocomplete file added for maigret
[Maigret docs](https://maigret.readthedocs.io/en/latest/#)

feat(maigret): add completion specs

---

src/remotion.ts

Updates to [Remotion](https://remotion.dev) CLI
Flags for an outdated version
Everything up to date
I will periodically batch together new flags and make a PR.

feat(remotion): add new flags

---

src/sapphire.ts

Adds completion spec for the [Sapphire CLI](https://github.com/sapphiredev/cli)

feat(sapphire): add spec

---

src/awsume.ts

Feature
N/A
Predict values for the awsume command
awsume github: https://github.com/trek10inc/awsume

feat: add spec for awsume

---

src/env.ts

adds a completion spec for env
fixes #1551 
no spec for env
completion for env, with custom generator for excluding existing environment variables
NA

feat(env): add completion spec

---

src/charm.ts

New completion for the [Charm](https://charm.sh/) CLI.
There is no completion for the Charm CLI.
There will be completion for the Charm CLI.

feat(charm): Add completion

---

src/git-cliff.ts

Adds completion spec for [git-cliff](https://github.com/orhun/git-cliff)

feat(git-cliff): add completion spec

---

src/swift.ts

feat(swift): update options

---

src/pg_dump.ts

Add new spec
Missing spec for `pg_dump` (Closes #1544)
Spec added for `pg_dump`

feat(pg_dump): add pg_dump spec

---

src/gum.ts

New spec for `gum`
Missing spec for `gum` (#1547)
Add spec for `gum`

feat(gum): add gum spec

---

src/watchman.ts

Added missing spec. Closes https://github.com/withfig/autocomplete/issues/1564

feat: add watchman spec

---

src/trap.ts

New spec
Closes #1531
Add trap spec

feat(trap): add trap spec

---

src/gem.ts

Adds completion spec for two subcommands of `gem`.
Missing completion spec.
**What is the new behavior**
Implemented completion spec.

feat(gem): add update & outdated subcommands

---

.all-contributorsrc
src/mongoimport.ts

Feature
Missing spec for mongoimport
Add spec for mongoimport

feat: add spec for mongoimport

---

src/asar.ts

- New spec
- Closes https://github.com/withfig/autocomplete/issues/1579
- Adds new spec for asar

feat: add spec for asar

---

src/pkill.ts

Added spec for `pkill`
closes #1540 
*i don't understand half these options lol*

feat: `pkill` spec

---

src/pkgutil.ts

Closes #1542 
Not implemented
* Question: is it possible to show 2 different descriptions depending on if an keyword argument is being passed? Reference to --pkgs subcommand with REGEXP?
* Please add hacktoberfest label

feat: add spec for pkgutil

---

src/grep.ts

fix: suggest current token for grep argument

---

src/zed.ts

- New spec
- Issue (fixes #1620 request)
- The spec as been added

feat: add spec for zed

---

src/gum.ts

Spec update for gum 0.8.0
Spec match gum 0.7.0
#1619
Spec match gum 0.8.0
Just wanted to do a shout out for the  amazing typing available and the eslint tools that make adding / updating a spec a breeze 😃

feat(gum): update spec for gum 0.8.0

---

.github/dependabot.yml

Add dependabot for automates dependency updates.

chore: add dependabot for npm and github-actions

---

src/rvm.ts

feat: add `rvm` spec

---

src/pipenv.ts

**What kind of change does this PR introduce?** 
closes #1645

fix(pipenv): `--quiet` spelling

---

src/visudo.ts

Pull request for issue (closes #1528) using [visudo's publicly available documentation](https://www.sudo.ws/docs/man/visudo.man/)
_Making my first contribution to Fig's Autocomplete Repo. Happy to make any changes if needed!_

feat: add `visudo` spec

---

src/goreleaser.ts

feat(goreleaser): update spec

---

src/csdx.ts

feature: initial completions for the ContentStack nodejs CLI tool csdx
[ContentStack](https://www.contentstack.com/) is a cloud-hosted CMS tool:
> Contentstack is an API-based, headless content management platform that allows developers and content managers to create and manage content simultaneously and independently, to create websites and applications quickly.
It provides a nodejs CLI tool for command-line interaction with your content stacks.
- https://www.contentstack.com/docs/developers/cli/

feat(csdx): add generator

---

src/dprint.ts

Feature
n/a
Completions for the dprint CLI
[dprint](https://dprint.dev) is an extendable code formatter for multiple programming languages

feat: add dprint spec

---

src/rojo.ts

Adds a new spec for [rojo](https://rojo.space/).

feat(specs): add rojo spec

---

src/surreal.ts

This PR adds a new spec for [SurrealDB](https://surrealdb.com/).

feat: add surrealdb

---

src/codesign.ts

Signed-off-by: Rosdyana Kusuma <rosdyana.kusuma@gmail.com>
closes #552
P.S. please add hacktoberfest label 🐱

feat(codesign): add completions

---

src/symfony.ts

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)** Feature
**What is the new behavior (if this is a feature change)?** Add symfony spec
**Additional info:** https://symfony.com/download

feat: add symfony spec

---

src/quasar.ts

feat: add quasar-cli framework spec. 
https://quasar.dev/start/quasar-cli

feat: add quasar-cli framework spec

---

src/pip.ts

fix: more permissive package search

---

src/echo.ts

fix: suggest current token for echo generator

---

src/cargo.ts

Adds better generators based on `cargo metadata`, adds generators for packages, bins, example, test, and bench. Also adds a generator for versions when using search on the `@` trigger.

feat(cargo): add more generators

---

src/figterm.ts

feat(figterm): add spec

---

src/cargo.ts

feat(cargo): more updates

---

src/fig/2.0.0.ts
src/fig/index.ts
src/fig/shared.ts

feat(fig): add spec for 2.0.0

---

src/kdoctor.ts

Ref: [KDoctor](https://github.com/Kotlin/kdoctor)

feat(kdoctor): add autocompletion spec for KDoctor

---

src/conda.ts

fixes #1625 (i think)
I couldn't find much info about this command :shrug:

conda env remove

---

src/systemctl.ts

feat: add `systemctl`

---

src/ditto.ts
src/man.ts

feat: add man ditto

---

src/brew.ts

changes `--formula,` to the correct `--formula`

brew --formula option fix

---

src/wing.ts

Add new autocompletion spec for [Wing](https://www.winglang.io/) CLI
N/A
Autocomplete for Wing CLI
[Wing website](https://www.winglang.io/)

feat: add Wing completion spec

---

src/npm.ts

pref 
close #275
close #974
use https://api.npms.io/v2/search/suggestions?q=%q&size=20

fix(npm): improve package suggestions

---

src/npx.ts
src/sta.ts
src/swagger-typescript-api.ts

feature
n/a
Adds a new spec for [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api)

feat: add swagger-typescript-api completion spec

---

src/go.ts
src/ls.ts

adds completion spec for the Go [workspaces](https://go.dev/doc/tutorial/workspaces)

feat(go): workspace spec

---

src/fig/2.0.0.ts

feat(fig): update spec for 2.9.0

---

src/fig/2.0.0.ts

feat(fig): add fig wrapped

---

src/fig/2.0.0.ts

feat(fig): update spec to `2.10.0`

---

src/npm.ts

https://github.com/withfig/autocomplete/pull/1728#discussion_r1038179446
Wrong code suggestion causes search to not work.😅
@fedeci

fix(npm): search does not work

---

src/sha1sum.ts

https://manpages.ubuntu.com/manpages/jammy/en/man1/sha1sum.1.html

feat: add `sha1sum` spec

---

src/chsh.ts

https://man.archlinux.org/man/chsh.1.en

feat: add `chsh` spec

---

src/fig/2.0.0.ts

feat(fig): update spec to 2.11.0

---

src/cdk8s.ts

Adds [cdk8s](https://cdk8s.io/) completion spec

feat: add cdk8s completion spec

---

src/argo.ts

Added completion spec for argo, the CLI for the kubernetes workflow orchestrator
Created from the argo cli reference
https://argoproj.github.io/argo-workflows/cli/argo/

feat: add argo spec

---

src/simctl.ts
src/xcrun.ts

feature
n/a
Adds a new spec of simctl (xcrun simctl ....)
Partially resolves #847

feat: add simctl completion spec

---

src/do-release-upgrade.ts

Info taken from https://manpages.ubuntu.com/manpages/bionic/en/man8/do-release-upgrade.8.html

feat: add ubuntu `do-release-upgrade` spec

---

src/ruff.ts

Spec for the [Ruff](https://github.com/charliermarsh/ruff) linter for python, generated with the [clap](https://fig.io/docs/guides/integrating/integrations/clap) integration

feat: add spec for `ruff`

---

src/fig/2.0.0.ts

feat(fig): update spec to 2.13.0

---

src/kind.ts

Adding completion spec for [kind](https://github.com/kubernetes-sigs/kind/) - Kubernetes IN Docker - local clusters for testing Kubernetes

feat: add kind

---

src/tldr.ts

This PR fixes the completion spec `tldr`
Closes #1826
Sgned-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

feat(tldr): update to latest version

---

src/circleci.ts

Update the `circleci.ts` CLI file with more info and new commands
Using older circleci CLI commands
Uses updated circleci CLI commands

feat(circleci): update spec

---

src/homey.ts

https://www.npmjs.com/package/homey

feat: add `homey` completion spec

---

src/gem.ts

feature
N/A
Add more gem subcommands
According to the [official document](https://guides.rubygems.org/command-reference/), GEM has the following commands:

feat: add gem subcommands

---

src/eas.ts

Adds EAS-CLI completion spec
N/A
Autocomplete EAS-CLI commands
https://github.com/expo/eas-cli

feat: add EAS-CLI completion spec

---

src/yalc.ts

feature
n/a
Adds a new spec for [yalc](https://github.com/wclr/yalc). 
Been using (and loving) fig for a long time now -- figured I'd add a spec for a cli I've been using frequently.

feat: add `yalc` spec 

---

src/luz.ts

This PR adds Fig completion for my project Luz, which serves as a build system for Apple Darwin-based systems.

feat: add `luz` completion spec

---

src/docker.ts

Feature
Closes https://github.com/withfig/autocomplete/issues/841

feat: add docker buildx spec

---

src/unset.ts

Created unset.ts to add autocomplete functionality to unset command

feat: add `unset` spec

---

src/tb.ts

feat: add tinybird cli completion spec

---

src/dotnet.ts

Changed the icon source to a working url.

fix(dotnet): update icon

---

src/tkn.ts

Added completion spec for [tkn](https://tekton.dev/docs/cli/) - A CLI for interacting with Tekton!

feat: add tkn spec

---

src/clilol.ts

[clilol](https://mcornick.com/clilol) is a CLI for the various fun services offered by [omg.lol](https://home.omg.lol).

feat(clilol): add spec

---

src/envchain.ts

This PR adds [envchain](https://github.com/sorah/envchain) completion specs.

feat: add envchain completion spec

---

src/clilol.ts

feat(clilol): update spec

---

src/aws-vault.ts

This PR adds [aws-vault](https://github.com/99designs/aws-vault) completion spec.

feat: add `aws-vault` spec

---

src/ghq.ts

This PR adds [ghq](https://github.com/x-motemen/ghq) completion spec.

feat: add ghq completion spec

---

src/rome.ts

This PR adds completion spec for  [Rome Tools](https://rome.tools/)
https://user-images.githubusercontent.com/62795688/229885049-69dfac40-0445-48f9-957d-64f7170066aa.mp4

feat: add spec for rome tools

---

src/dcli.ts

feature
n/a
Adds a new spec for [dcli](https://github.com/Dashlane/dashlane-cli)
n/a

feat: add spec for dcli cli

---

src/valet.ts

update spec inline with new commands from v4.
update some existing commands optional arguments.
update help command to use generator.

feat(valet): update spec for v4

---

src/yomo.ts

Hi Fig!
YoMo is an open source Streaming Serverless Framework to help developers with their Geo-distributed Applications. `yomo` is the CLI tool. Our community members love Fig so we want to Fig can help our developers too!
More about YoMo can be found here: https://github.com/yomorun/yomo

feat: add yomo completion spec

---

src/ipatool.ts

feature
n/a
Adds a new spec for [ipatool](https://github.com/majd/ipatool)
n/a

feat: add `ipatool` completion spec

---

src/nx.ts

Reverts withfig/autocomplete#1915

Revert "feat(nx): add support for project json"

---

src/ncu.ts

Adds support for https://www.npmjs.com/package/npm-check-updates aka `ncu`

feat(ncu): add support for npm-check-updates

---

package.json
src/echo.ts

chore: bump fig/autocomplete-generators and withfig/autocomplete-types

---

.vscode/settings.json
src/nx.ts

See https://github.com/withfig/autocomplete/pull/1915 https://github.com/withfig/autocomplete/pull/1929
Issue https://github.com/withfig/autocomplete/issues/1928

feat(nx): update spec

---

src/astro.ts
src/npx.ts

feature
n/a
Adds a new spec for [astro](https://docs.astro.build/en/reference/cli-reference/)
n/a

feat: add `astro` spec

---

src/suitecloud.ts

Used for NetSuite development with SDF

feat: add support for SuiteCloud CLI

---

src/northflank.ts

This pull request builds on #1410 and updates the fig autocompletion spec for the Northflank CLI (https://www.npmjs.com/package/@northflank/cli) reflecting API schema changes of the recent months.
The specification was fully autogenerated using the `@fig/complete-commander` package and passed `npm run test` as well as `npm run lint`.

feat(northflank): update completion spec

---

src/npx.ts
src/playwright.ts

Feature
Does not support Playwright commands
Added support for few commands used by playwright

feat: added support for Playwright

---

src/nx.ts

Fix for this issue: https://github.com/withfig/autocomplete/issues/1928#issuecomment-1549362491
@fedeci I believe @overbit would be happy if this will be released fast :)

fix(nx): Fixed typo in appsDir

---

src/cd.ts

This PR adds the support of `~` suggestion in cd spec. 
Fixes: #1938

feat(cd): add suggestion to home directory

---

src/sidekiq.ts

Hello everyone 😄 
I'm working on adding an autocompletion spec for [sidekiq](https://github.com/sidekiq)!

feat: add `sidekiq` cli autocompletion specs 🚀 

---

src/palera1n.ts

palera1n is a jailbreaking tool for iOS/iPadOS 15.x-16.x arm64.
https://github.com/palera1n/palera1n

feat: add `palera1n` completion spec

---

src/poetry.ts

Hi👋🏻 This PR updates `poetry`'s specification to follow the new version of `poetry` v1.5.
Documentation: https://python-poetry.org/docs/cli
Thanks for your review! 😉

feat(poetry): update spec

---

src/git-quick-stats.ts

add completion spec for [git-quick-stats](https://github.com/arzzen/git-quick-stats/) program

feat:add git-quick-stats spec

---

src/gron.ts

Add completion spec for [gron](https://github.com/tomnomnom/gron) program
I have read the CLA Document and I hereby sign the CLA

feat(spec): add new gron for spec

---

src/starkli.ts

Hey all! As per discussion with Matt Schrage on the fig Discord, I'm opening a PR to support Starkli in Fig!
Resolves #2036

feat: add starkli completion spec

---

src/bun.ts

Bun recently added a debugger, to use it you need a couple of flags, this PR adds them
https://bun.sh/guides/runtime/web-debugger

fix(bun): Add --inspect family of flags

---

src/kdoctor.ts

Ref: [KDoctor](https://github.com/Kotlin/kdoctor)

feat (kdoctor): updated autocompletion spec for KDoctor

---

src/dcli.ts

feat
Old spec was written for version 1.1.0
Updates spec for [dcli](https://dashlane.github.io/dashlane-cli) to version 1.14.2
n/a

feat(dcli): update spec to latest dcli version 1.14.2

---

src/expressots.ts

Feature Add ExpressoTS spec
**ExpressoTS** 
The Developer-Friendly TypeScript Framework for Server-Side Applications
[Site](https://expresso-ts.com/) [Github](https://github.com/expressots/expressots) [Linkedin](https://www.linkedin.com/company/expresso-ts/)

feat: add expressots spec

---

src/bit.ts

Add support for the bit Cli tool
https://bit.dev/reference/reference/cli-reference

feat: add bit spec

---

src/sort.ts

Add support for the `sort` CLI tool.

feat: add `sort` spec

---

src/idea.ts

added  [Command-line interface for IntelliJ IDEA](https://www.jetbrains.com/help/idea/working-with-the-ide-features-from-command-line.html)

feat(idea): add spec

---

src/nmap.ts

This PR introduce the feature **nmap**

feat: add `nmap`completion spec

---

src/pulumi.ts

Add autocomplete for stacks in pulumi

feat(pulumi): Autocomplete stack-name

---

src/doppler.ts

this contribution adds generator support for several of the project-specific settings that occur when using the doppler CLI.

update Doppler spec

---

src/plutil.ts

Feature
No completion spec for plutil currently exists ([issue that requested this feature](https://github.com/withfig/autocomplete/issues/1541))
Added completion spec for plutil

feat(plutil): Added completion spec for plutil

---

src/bun.ts
src/bunx.ts
src/npx.ts

- Add bunx and "bun x" spec
- Add npx create specs to bun create

feat(bunx): Add bunx spec and x alias to bun

---

src/date.ts
src/svn.ts

Feature
Currently not available
Partial support for SVN auto-completion
Added support for a few subcommands. But I'll continue improving the spec by adding more properties to the spec

feat: add svn completion spec

---

src/dpkg.ts

fixes #1432
Adds the dpkg spec

feat: Added dpkg spec

---

src/@capgo/cli.ts

This PR adds spec for [Capgo](https://capgo.app/) it's a big tool in Ionic Ecosystem

feat: add capgo spec

---

src/deno.ts
src/deno/generators.ts

feat(deno): update generators

---

src/cut.ts

This PR closes #2174 and updates the `cut` utility specification.

feat(cut): add -w flag

---

src/nx.ts

fix(nx): cache generation issue due to wrong shell command

---

src/infracost/0.10.0.ts
src/infracost/index.ts

Feature
Infracost CLI v0.10.x has incomplete/incorrect autocompletion
Autocomplete support has been added for Infracost CLI v0.10.x
The new spec is generated using cobra-cli and [Fig's tutorial](https://fig.io/docs/guides/integrating/integrations/cobra).

feat(infracost): Add spec for Infracost CLI v0.10.x

---

package.json
yarn.lock

This PR should add support for dev mode in CodeWhisperer for command line.

deps: Bump @withfig/autocomplete-tools to 2.8.0

---

src/rails.ts

- Add rails notes command
- Add args

feat(rails): rails notes command

---

src/remotion.ts

A few new options we added!
Btw, I know there are better options to submit it automatically, we still plan to do it in the long-term and automatically derive Fig schemas from our actual logic.
For now, I just submit the file that we semi-automate in our monorepo from time to time.

Update with newest Remotion options

---

src/npm.ts

In this PR I have added 2 options: verbose and registry, to npm install and npm clean-install commands.
Copied [this PR](https://github.com/withfig/autocomplete/pull/2242) because of the wrong commit author.

feat(npm): enhance npm completion

---

src/node.ts

Resolving #2262  
(previously submitted as https://github.com/withfig/autocomplete/pull/2263 )

[node] Add .cjs extension to `node` file suggestions

---

src/asciinema.ts
src/go.ts

The description for asciinema had a typo, this fixes that.

feat(asciinema): fix typo

---

src/php.ts
src/php/artisan.ts

This PR fixes a bug in the PHP spec where Promise.all() was not implemented correctly. It also filters an internal Laravel command for the artisan spec.

fix(php|artisan): resolve promises correctly

---

src/tailcall.ts

This PR adds completion spec for [Tailcall](https://tailcall.run/)
https://github.com/user-attachments/assets/8bc18fa9-bc00-494b-a286-ff48c626e705

feat: completion spec for tailcall.run

---

src/kotlinc.ts

Added spec for kotlinc-jvm given at - https://kotlinlang.org/docs/compiler-reference.html
closes #1326
https://github.com/user-attachments/assets/abf64e1d-a005-4cd6-afc0-a92382842c2f

feat(kotlinc): add kotlin spec

---

src/lvim.ts

This PR adds completion spec for lvim (lunar vim). Same as nvim (neovim). Closes #1925
https://github.com/user-attachments/assets/22612f7b-e8a2-4bbb-8909-90543a7cb251

feat(lvim): add completion spec

---

src/herd.ts

Add completion spec for [Laravel Herd](https://herd.laravel.com/)

feat: add Laravel Herd completion spec

---

src/shasum.ts

This PR adds completion spec for `shasum` built-in utility for OS X & Linux

feat(shasum)

---

src/eza.ts

Add initial spec for [eza](https://github.com/eza-community/eza).

feat(eza): add spec

---

package.json
pnpm-lock.yaml

- **Add exports to package.json**
- **chore: update deps**

 chore: update deps 

---

src/zellij.ts

Zellij specs have been updated to the latest version.

feat(zellij): update spec 

---

src/ampx.ts

update ampx command options 
https://docs.amplify.aws/react/reference/cli-commands/

update ampx command options
