withfig/autocomplete

specs/tar.js

Something to think about ... should the specs be organized per 'OS' (in anticipation of support of different platforms).

Add spec for tar

---

specs/brew.js

This PR adds completion spec for `brew services`. I have included a generator for listing the different services a user has installed on their machine. It is used with each of the `brew services` subcommands outside of `cleanup` and `list`.
I am accomplishing this listing using `brew services list | sed -e 's/ .*//' | tail -n +2`. There may be a more elegant way to grab that input data, so I would love some criticism on it. :grin:

Add completion spec for brew services

---

specs/git.js

Expanding the autocomplete spec for Git to support options that come before the subcommand, e.g. I often use `git --no-pager diff <file>`.
Currently no support for options before subcommand

add pre-subcommand Git options

---

specs/vi.js

Adds a new (very basic) spec for `vi`
No autocompletion on files when using the `vi` command
Shows an autocompletion list of files to open with `vi`

Add vi.js to autocomplete

---

specs/git.js

This PR adds the `--skip` flag to the autocomplete for `git rebase`
Right now, there is no autocomplete suggestion for `--skip`
`--skip` is now an autocomplete option
N/A

feat: add `git rebase --skip` to git spec

---

specs/docker-compose.js

Feature
The current behaviour is to autocomplete the options but not the arguments
Autocomplete the arguments where possible with the services from a docker-compose.yml

docker-compose: Autocomplete services from root docker-compose.yml

---

package-lock.json
specs/git.js

This adds all options and args for the `git fetch` command.
The options `--recurse-submodules` and `--recurse-submodules-default` are currently not active, because the delimiter `=` is currently not working

Update git fetch

---

specs/vue.js

Feature: adding basic definitions for vue-cli auto completion
Currently there are no specifications for vue-cli commands
This will add specifications for vue-cli commands.

adding specs for vue cli

---

specs/kubectl.js

feature
No arguments for `get`
Generator to get the resources using `kubectl api-resources -o name`

feat(kubectl): get generator for resources

---

specs/git.js

This adds all specs from the `git commit` and `git config` command.
I will be doing some more specs for git in the next weeks, but I have exams next week so this will have to wait a bit.
For generating the specs I am using something self written which can be used:
https://github.com/Jubeki/fig-git-fetcher

Update `git commit` and  `git config`

---

specs/gh.js

Feature: autocomplete spec for `gh clone` subcommands
currently no `ch clone` subcommands have autocomplete spec
`gh clone` subcommands now autocomplete
Info taken from https://cli.github.com/manual/gh_repo_clone

Add `gh clone` completions

---

specs/flutter.js

Feature
Flutter 2.0.1 command autocompletion is not implemented yet
Add Flutter 2.0.1 command autocompletion
None

Add Flutter 2.0.1 CLI Autocompletion

---

dev/pod.ts
specs/pod.js

Added CocoaPods spec generated using(mostly) a recursive script and the `--help` option
No specs for `pod`
Now, `fig` autocomplete `pod` 
*none*

feat: Added CocoaPods spec

---

dev/brew.ts
specs/brew.js

Bug fix
Search path for formulas and casks in brew install subcommand generator is wrong for homebrew installations in new M1 macs. On M1 macs homebrew installs in /opt/homebrew while on Intel macs is in /usr/local/Homebrew 
By using the command "brew --repository", the right homebrew installation path can be used for any mac.

Fix search path in brew install subcommand generator

---

dev/npx.ts
dev/react-native.ts
specs/npx.js
specs/react-native.js

Added spec for standalone `react-native`'s cli and also for when using it from `npx`(`npx react-native [command]`)
See #87 
**What is the current behaviour? (You can also link to an open issue here)**
No specs for `react-native`
Some of the generators created, fail sometimes because some of the commands used inside the `script` timeout. Unfortunately, I couldn't figure out exactly a way to avoid that

feat: Added spec for react native cli and npx

---

dev/yarn.ts
specs/yarn.js

Feature
When running `yarn <scriptname>` or `yarn run <scriptname>` the yarn icon doesn't appear like it does when invoking `npm run <scriptname`
The icon is displayed

feat: add yarn icon for scripts from package.json

---

package.json
scripts/compiler.ts
scripts/create-boilerplate.sh

Feature
It is not possible to nest files in the `dev/` folder (e.g. `dev/aws/s3.ts`)
It is possible to nest folders.
Updated eslint, typescript and also the `copy` and `copy:all` commands

[FIG] feat: allow nesting of specs

---

.github/workflows/danger.yml
dev/npm.ts
specs/npm.js

Feature
Npm install returns packages that are already in the package.json
Uses`npm search` to search as you are typing

[NPM]: feat: npm install autosuggests from npms.io

---

schemas/fig.d.ts

Checked all the typescript definitions to make sure they match the old docs. Made a few changes, but most of it looks consistent

match type descriptions to docs

---

schemas/fig.d.ts

Bug fix
The property `priority` is misspelled in our schema `fig.d.ts`file
The typo is fixed

[FIG]: fix typo in schema

---

dev/expo.ts
specs/expo.js

Small feature allowing `expo <command>` to trigger the same autocomplete as `expo-cli <command>`.
Typing `expo` alone does not prompt autocomplete, while typing `expo-cli` does prompt autocomplete.
Typing `expo <command>` exposes the same autocomplete as `expo-cli <command>`.
Both `expo <command>` and `expo-cli <command>` have the same functionality. The former is much more common in docs, tutorials, use, etc.

[EXPO] add autocomplete functionality for expo command in addition to expo-cli

---

schemas/fig.d.ts

Docs update
The `posixNoncompliantFlags` property does not exist on the `Spec` type
The `posixNoncompliantFlags` exists as a property on `Spec`

feat: add posixNoncompliantFlags to Spec

---

dev/open.ts
specs/open.js

Fix
You can't open a folder, Fig insist to go deeper: 
Allow opening folders

[OPEN] Allow opening folders

---

dev/git.ts
specs/git.js

FIX - git checkout command can be used to restore files from the working tree and checkout branches
Current autocompletion only documents the branch
Added description to talk about the file checkout too

[GIT] Add commit to `checkout` name and description 

---

dev/yarn.ts
specs/yarn.js

This PR adds a new feature to the `yarn` spec
Currently, if you want to run a cli from yarn using `yarn <cli> ...`, you won't get any completion
Fig loads the specs of the cli that are in the current `package.json` and provide completion for them
Example:
The `next` package exists in the current `package.json`, so the spec for it will be loaded.

[YARN]: Load specs of cli that exists in current package

---

dev/jest.ts
specs/jest.js

Feature
Options of Jest's spec doesn't have any template
Adds `filepath` template to needed options to get autocompletion on them

[JEST] Improve Jest spec

---

dev/brew.ts
specs/brew.js

I added the `brew analytics <on|off>` command to Fig autocomplete specs. People like to turn the analytics off for privacy reasons.
Fig `brew` autocomplete does not list this subcommand.
Fig will show the autocomplete for the following:
- `brew analytics`
- `brew analytics on`
- `brew analytics off`
N/A

[BREW] Add analytics subcommand

---

.gitignore

Feature
Contributors need to check in their newly created `.js` files in as well
New PRs only have to include the `.ts` file
The files are still in git for compatibility with old versions of Fig

feat: add specs folder to gitignore

---

dev/cut.ts
specs/cut.js

Adds specs for the cut command
No specs exist for the cut command
cut command autocompletion is enabled

[CUT] Add spec for cut

---

scripts/eslint-plugin-fig-linter/rules/no-empty-array-values.js

Feature
The eslint rule disallows empty `options` and `subcommands` arrays at the root command
Those are now allowed and don't cause an error

[INTERNAL] feat: update no-empty-array-values rule

---

dev/git.ts

I guess this is a feature. Here are the changes:
1. Add a generator for getting staged files using `git diff --name-only --cached`, check [here](https://stackoverflow.com/a/33610683).
2. Adds `file` as an option to the first argument of `git diff`.
resolves #235 - previously only commits and unstaged files were being displayed.

[GIT] Add file to possible list of arguments for diff

---

dev/yarn.ts

**What kind of change does this PR introduce? ** feature
**What is the current behavior?**  No flag auto-completion to yarn upgrade-interactive
**What is the new behavior (if this is a feature change)?**  Add --latest flag to yarn upgrade-interactive command
**Additional info:** Haven't tested it. See https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive/#toc-yarn-upgrade-interactive command documentation

[YARN] Add --latest flag to upgrade-interactive

---

dev/git.ts

Bug fix
Writing git push does not auto-complete `git push --force-with-lease` 
**What is the new behavior (if this is a feature change)?** 
Autocompletion for `git push --force-with-lease` 
Haven't tested it locally, but it seems like a small typo

[GIT] Fix --force-with-lease option

---

dev/expo.ts

Feature
The new subcommand `run:ios` and `run:android` does not exist
Added those new subcommands
Blog-post of the expo CLI update:
https://blog.expo.io/introducing-expo-run-commands-835ae8da4813
Preview:

[EXPO] Add new subcommands

---

dev/git.ts

Bug fix
https://github.com/withfig/fig/issues/107

[GIT] Ignore warning, error message

---

dev/brew.ts

Feature
The subcommand `brew analytics regenerate-uuid` does not exist
Added subcommand
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/analytics.rb#L47
Preview

[BREW] Add regenerate-uuid subcommand

---

dev/electron.ts
dev/yarn.ts

Feature
No completion spec for `electron`
Add a completion spec for `electron`
Also add it to `yarn` spec, to get completion like this:

[ELECTRON] Add electron spec

---

dev/echo.ts

Feature
No completion spec for `echo`
Add a (very very small) completion spec for `echo`

[ECHO] Add echo spec

---

dev/docker.ts

Feature
No 'compose' subcommand for 'docker' command
Add 'compose' subcommand to 'docker' command. No options/arguments were added due to a lack of familiarity with the most common options for this subcommand.
- [Docker compose docs](https://docs.docker.com/compose/cli-command/)
- Fulfills #245

feat: add 'compose' to docker spec

---

dev/npx.ts

This PR adds the `next` also as a subcommand of `npx`. I don't think it is a common practice to have `next`, `babel`, `tailwind`, etc...installed globally. 
Instead many `npm` CLI tools are convenient to be run as `npx --no-install [package-name]` from the project dir.
I think the same applies to other `npm` commands.

feat: add `next` subcommand to `npx`

---

dev/git.ts

This PR extends the existing `git` file to include an Argument generator which suggests git aliases (from config, not shell aliases).
Without this commands like `git st` become cumbersome with Fig as you have to <space> or <esc> away the menu to avoid the suggested vanilla command.

Add aliases generator for git completion

---

dev/git.ts

Bug fix for git cli. Current behavior when branch `other` is checked out in another worktree is to show `+ other` as a suggestion.
New behavior handles this case, suggesting `other` instead, while still handling branch names with the `+` character in them.

Remove preceding '+' for branches checked out in another worktree

---

dev/tailwindcss.ts

Update `tailwindcss` cli spec to the latest version according to https://github.com/tailwindlabs/tailwindcss/blob/8da840f2a3df2df6b4159d5c849a99536f2b8989/src/cli.js#L125-L164 and to the docs.

feat: update `tailwindcss` spec

---

dev/git.ts

Completion Spec Update
#312 
`git branch` is currently missing certain options such as `-r`
Adds missing options for `git branch`

Add missing options for git branch spec

---

dev/brew.ts

Feature.
Autocomplete is missing the `brew autoremove` command.
1. Add `autoremove` command
Brew docs about the `autoremove` command: https://docs.brew.sh/Manpage#autoremove---dry-run

[BREW] Add autoremove command

---

dev/docker/compose-build.ts
dev/docker/compose-create.ts
dev/docker/compose-events.ts
dev/docker/compose-exec.ts
dev/docker/compose-images.ts
dev/docker/compose-kill.ts
dev/docker/compose-logs.ts
dev/docker/compose-pause.ts
dev/docker/compose-ps.ts
dev/docker/compose-restart.ts
dev/docker/compose-rm.ts
dev/docker/compose-run.ts
dev/docker/compose-start.ts
dev/docker/compose-stop.ts
dev/docker/compose-up.ts
dev/terraform.ts

Bug fixes related to type errors not caught by TypeScript. See the commit messages for more details.
The definitions don't really match up with the types. It just turns out that TypeScript is so lenient that these don't actually cause a type error to occur.

Fix type issues

---

dev/sed.ts

[Sed] Add Completion Spec

---

dev/aws/elasticbeanstalk.ts

[AWS] [Beanstalk] generators

---

dev/git.ts

Bug fix
#339
Removes double-quotes using a regex at the start and/or at the end of each line of `git status --short` output

fix: Double quotes in git staged files generator

---

dev/git.ts

Adds `restore` subcommand to `git`.
#343

[git] Restore Subcommand

---

dev/git.ts

Add Wildcard Generator for staging files in git
#73 
Checks for matching paths of committed files and adds a suggestion for a wildcard.

[git] Add wildcard generator

---

.vscode/settings.json

Pulling this out from https://github.com/withfig/autocomplete/pull/354/files#r667475392
IMO this setting improves the default Fig spec editing dev experience without requiring everyone to manually set this in their global user VSCode settings 🙌 
When saving a Fig spec in VScode, prettier does not currently automatically run.
When saving a Fig spec in VSCode, prettier will automatically run.

Add editor.formatOnSave

---

dev/jq.ts

Feature
Adds `jq`, but doesn't actually provide suggestions for the filters that users can use. Only includes options and args that it takes.
https://code.tools/man/1/jq/

[jq] Add Minimal Spec

---

dev/aws/acm.ts

[AWS] [ACM] add generators

---

.vscode/settings.json
dev/django-admin.ts
dev/python.ts
dev/python3.ts

This PR adds the Django spec, meaning auto complete for `django-admin <command>` and `python manage.py <command>`
Closes #298 
I originally went down the path of dynamically auto generating this whole spec at runtime based on the help output provided by `django-admin` script. This has the benefit that we'd show suggestions for exactly those commands that are available, including custom-defined management commands. 
But I think there are some problems with that dynamic approach at the moment. Notably, from a user's perspective, it's slower and requires regular manual set up (ie running `fig set:path`). So i've decided to just stick to a fully static spec for now and circle back to the dynamic approach in the future. If …

Add Django Spec

---

dev/git.ts

This adds the ability to prioritize unstaged files in the suggestions for git add. This feature was suggested in https://github.com/withfig/autocomplete/issues/376

Git prioritize unstaged files

---

dev/bazel.ts

New feature request for Bazel
https://github.com/withfig/autocomplete/issues/255
this copy works but has an issue where it will only pickup Bazel target suggestions from one Bazel BUILD file. Not sure if using the custom flag in the generator over postProcess would make a difference or not. I think the script command is returning before the for loop opens and prints the contents from all of the Bazel build files to the command line.

[bazel] Bazel support

---

dev/aws/cloudwatch.ts

[AWS] [Cloudwatch] add generators

---

dev/docker.ts

On input from issue https://github.com/withfig/autocomplete/issues/304 changed the Docker autocomplete generator to show container names rather than the IDs it currently shows.

[Docker] show container names rather than the IDs

---

dev/git.ts

Feature
The current branch is distinct by a ⭐️  icon, but can be anywhere in the suggestions
Adds a priority of `100` to the current branch so it will always stay at the top
Very useful in this case:

[git] Prioritize current branch

---

dev/npm.ts

- Bug fixes
- Various bugs
- Add aliases of npm uninstall
- Changed icon & description of npm uninstall to make more sense
- Made npm uninstall variatic to process multiple uninstalls
- Fixed bug with npm uninstall not working with packages including @, by using a displayName
- Addresses #390 and #391

feat: fix bugs in npm uninstall

---

dev/git.ts

Feature
git checkout will list branches, files, and commits to checkout but not tags.
Tags will be listed in the suggestions for git checkout.
The current branch is normally given top priority with a star icon. However, if we are in a detached HEAD state after checking out a tag, I don't think we want to suggest the current branch. It would just show (detached HEAD state) and isn't actionable suggestion.
Re:https://github.com/withfig/autocomplete/issues/403

git[checkout]: show tags in checkout suggestions

---

dev/git.ts

This PR adds in the --no-optional-locks flag everywhere git status is run as a background command.
A index.lock file will not be created when status is run so user git commands will not be blocked from running.
Bug fix
Background `git status` commands create an index.lock file which can interfere with user commands if the repo is large enough. The .lock file is still in place while Fig is generating completions and blocks the user from exec their own command.
Skip creating the .lock file when we run git status.
See explanation: …

git: use --no-optional-locks with background status cmd

---

dev/create-react-native-app.ts
dev/npx.ts
dev/pnpx.ts

Adds support for `create-react-native-app`. Utilizes the icons added for https://github.com/withfig/autocomplete/pull/419 (I maintain both tools).

feat: add create-react-native-app spec

---

dev/tmux.ts

Bug fix
fig autocompletes this way:
`tmux new -S 'name'`
Which throws an error:
```sh
$ tmux new -S 'session1' 
tmux: unknown option -- S
```
```sh
$ tmux new -s 'session1' 
```

fix: [TMUX] session name flag '-s' should be in lowercase

---

dev/autojump.ts
dev/j.ts

Feature
There is no support for autojump
Re: https://github.com/withfig/autocomplete/issues/438
This adds support for autojump and its alias j

Support for autojump and alias j

---

dev/hub.ts

Feature
Many people use Github's hub CLI tool as a wrapper and alias for git. When typing git, they expect autocompletions but don't get anything due to Fig reading the command as 'hub' and seeing no applicable spec.
hub gives the same exact suggestions as git. There are additional features that hub provides but I have not added them in.
Per hub's README: "Some hub features feel best when it's aliased as git. This is not dangerous; your normal git commands will all work. hub merely adds some sugar."
There shouldn't be any issues using the git completion spec with …

[hub] as wrapper for git

---

dev/git.ts

Per `man git-branch`: the -d and -D options take a branch arg that is variadic. You can also use in conjunction with -r to delete remote branches.
This PR makes those arguments variadic and also adds a generator that generates either local or remote branches depending on whether -r is being used.

[git] branch -d & -D arg is variadic

---

dev/lsd.ts

lsd was previously a wrapper for ls but they don't have the same options or arguments.
Completed spec to match lsd --help

Completed lsd spec

---

dev/echo.ts

The argument is self explanatory as echo only does one thing. The description box was very long despite how simple the argument is.

[echo] Changed arg name to string and removed description

---

dev/fnm.ts

Feature
Adds a spec for the [`fnm` node version manager](https://github.com/Schniz/fnm)
If you want to compare it to the fnm's help command, it is available [on their github](https://github.com/Schniz/fnm/blob/master/docs/commands.md).
**What is the new behavior (if this is a feature change)?** /
**Additional info:** 
As this is my first contribution to Fig, don't refrain from suggesting how the spec could be improved or what I should maybe do differently. I'm happy to discuss! :)

Add fnm spec

---

dev/ionic.ts

Adds autocomplete spec for Ionic CLI.
Working on the generator over here:[https://github.com/EthanOrlander/ionic-fig-generator]( https://github.com/EthanOrlander/ionic-fig-generator)
Hooking into the Ionic CLI using `ionic help --json` and programatically generating the spec.
- Turns out `ionic help --json` is incomplete and incorrect, so there's a bit of manual post-processing work 
Please let me know if there's any issues thus far!

Autocomplete spec for ionic cli

---

dev/git.ts

Complete spec for git cherry-pick. No new generators. 
Using existing commit generator for arg.
Also added descriptions to git commit --cleanup <modes> to match cherry-pick.

[git] cherry-pick

---

dev/npm.ts

[npm] Updates to several npm subcommands

---

dev/shortcuts.ts
this.txt

Feature
Backend doesn't exist
It does exist
The Shortucts app and this utility are currently available in the macOS Monterey Public Beta, slated for release this Fall.
https://www.apple.com/macos/monterey-preview/
https://sixcolors.com/link/2021/06/shortcuts-shaping-up-on-the-mac/
- `shortcuts list`
- `shortcuts list --folders`
- `shortcuts run HelloWorld`
- `shortcuts view HelloWorld`

feat: Add `shortcuts` spec (macOS Monterey)

---

dev/afplay.ts
dev/mv.ts

-R and -P are not options on mv so they were removed and replaced with -f, -i, -n, and -v
First arg should also be variadic

[mv] Fixed 1st arg and options

---

dev/fvm.ts

This PR adds autocompletion support for the fvm CLI (Flutter version manager).
Currently there is no autocomplete for fvm.
Autocomplete now works with all fvm commands and subcommands except the dart proxy command. When I get around to adding Dart autocomplete support I would like to add that to fvm autocomplete as well (the same way the flutter proxy is currently implemented).

feat: add fvm completion spec

---

dev/laravel.ts

This PR adds autocompletion support for laravel (Laravel Installer cli).
Missing support

feat: add laravel completion spec

---

dev/touch.ts

Touch spec was originally written for the GNU version but macOS ships with BSD. This PR changes the touch spec to comply with BSD (man spec on macOS).
Basic functions are the same but some of the options differ.

[touch] re-work per BSD spec

---

dev/find.ts

Adds basic args and options for `find`
The 2nd arg, expression, is actually a combo of 'primaries' and 'operands'. See `man find` for details on how this works. 
Not sure how best to offer suggestions on expressions based on Fig specs at this time.
This will at least provide basic suggestions for the find tool.
re: https://github.com/withfig/autocomplete/issues/493

[find] basic spec

---

dev/git.ts

man git-add:
<pathspec>
...Also a leading directory name (e.g.  dir to add dir/file1 and dir/file2) can be given to update the index to match the current state of the directory as a whole (e.g. specifying dir will record not just a file dir/file1 modified in the working tree, a file dir/file2 added to the working tree, but also a file dir/file3 removed from the working tree)...

Pathspec arg can be a dir

---

dev/git.ts

The argument for `git clone --recurse-submodules` is optional but the insertValue of "--recurse-submodules=" made it appear mandatory.
Users would need to backspace the '=' after entering the suggestion or believed that the arg was mandatory.

[git] remove insertValue from clone --recurse-submodules

---

dev/graphcdn.ts

Feature
No spec in place
There is a spec

[GRAPHCDN] add initial spec

---

dev/git.ts

git stash pop takes an optional arg. However the spec had an insertValue of 'pop {cursor}' which made it seem as if the arg was mandatory.
This makes it so completing on pop will not add a space or make fig popup again.

[git] stash pop arg fix

---

dev/kubecolor.ts

Adds support for [kubecolor](https://github.com/dty1er/kubecolor), a tool which colorizes kubectl output. It takes identical arguments to kubectl as under the hood it just invokes kubectl and reformats the output.
No completions are given for kubecolor or kubectl when kubecolor is used (assuming it is aliased to kubectl).
Support completions for both `kubecolor` and an alias from `kubectl` to `kubecolor`.
This PR just re-exports the completions from kubectl as kubecolor.

feat: add completion spec for kubecolor

---

dev/pwd.ts

pwd spec was written according to GNU spec so there were some incorrect options.
Re-wrote according to the BSD version (`man pwd` on macOS).

[pwd] redo per BSD spec

---

.eslintrc.js
package-lock.json
package.json

Feature
Completion specs can use Browser APIs that are supported in newer versions of WebKit, but break when run on older machines.
Add `eslint-compat-plugin` to check for the use browser APIs that are not supported across all necessary versions of Safari (WKWebview).

Add linting for unsupported browser APIs

---

schemas/fig.d.ts

No support for options that should be carried down to child subcommands.
No-op change but adds ability to indicate options as persistent to support these types of options in the future.

Add persistent option flag on options

---

dev/xargs.ts

Feature: completion spec for `xargs`
This is BSD xargs (since Fig is macOS only right now) - a port to Linux, where GNU is the norm, would require changing this.

feat: add xargs completion spec

---

dev/git.ts

Bug fix / polish
Some git commands suggest `HEAD` as an argument; others suggest `HEAD~`.
This standardizes all git commands that suggest one of these to suggest both. In particular, this resolves a nasty issue where `git reset --hard` ONLY suggested `HEAD~`. As a result, by hitting enter twice, the user would automatically throw away the latest commit.
**Test plan:**
I tried the commands in my terminal and everything seemed to work.

Include both `HEAD` and `HEAD~` as git suggestions

---

dev/nativescript.ts
dev/ns.ts
dev/tns.ts

Feature: added the NativeScript completion spec
ns, tns and nativescript autocompletion specs have been introduced to Fig
fixes #553

feat: add nativescript completion spec

---

dev/git.ts

A single dash can be used as an arg for git merge as shorthand for "the previous branch"
See git 1.7.6 release notes https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.6.txt#L84

[git] Add single dash as arg for merge

---

dev/deno.ts

Feature: Improves `deno doc` suggestions 🎉
---
<details>
<summary><b>Screenshots</b> (warning: very compelling)</summary>
<br>
_Fig. 1. Top-level results for a file_
_Fig. 2. Results for members of `API`_
_Fig. 3. Private symbols work, too!_
Aside: I can't use `src/models.ts` with `--private` because it causes a stack overflow in Deno! So that's fun.
</details>
---
Suggests files to doc, doesn't suggest a filter.
Uses the scope (the file) to suggest a filter as you type. It really does Just Work(tm).
It's a relatively complicated generator but it runs …

feat(deno): add generator for doc filters

---

src/brew.ts

Bug fix / Feature
Missing `--overwrite` option to `brew link`.
Missing `brew unlink` command.
Add `--overwrite` option to `brew link` and `brew unlink` command.

Add brew unlink command

---

src/nocorrect.ts

Adds the `nocorrect` spec
Prezto add `nocorrect` to a many aliases [by default](https://github.com/sorin-ionescu/prezto/blob/515d70f639d76314801bbae7e5f1e20da8a76000/modules/utility/init.zsh). This PR ensures that despite this, Fig will still show proper completions.

[nocorrect] Add spec

---

dangerfile-invite.ts
src/fig.ts
src/gh.ts
src/ns.ts
src/pipenv.ts

Docs: Use 'GitHub' instead of 'Github'

---

src/npm.ts

--legacy-peer-deps is a common option used with npm install but it is not in the current spec.
This option tells npm to skip installing peer dependencies. It is most commonly use when building a react app with react >= 17 and installing packages that don't explicitly have react >= 17 listed as a peer dependency.
This flag tells npm to behave as it did in versions v4 - v6 when installing packages.
https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh
Re: https://github.com/withfig/autocomplete/issues/545

[npm] Add --legacy-peer-deps for npm install

---

src/cargo.ts

Improves existing spec
Improves `cargo` support, adds all of the "common" cargo commands and adds most options for them. New commands: check, clean, doc, new, run, bench, install, uninstall, search
None

feat: Add all common cargo commands and more options

---

src/htop.ts

New feature: add htop completion spec
There is no current behavior.
The new behavior is to show completion options for the `htop` command.
None.

feat: add htop completion spec

---

.gitignore
package.json
src/npm.ts
src/pnpm.ts
src/yarn.ts

closes #571
closes #602 
Improving existing specs:
Just add `add` alias. Nothing more.
- Removed weird code that was displaying `autocomplete-tools` instead of `@withfig/autocomplete-tools`. This code didn't make any sense to me:
https://github.com/withfig/autocomplete/blob/d90f2963006c427c1f621608b0b00e031fd9629b/src/pnpm.ts#L51
- Add missing `isVariadic` in all generators
- Reordered options for install commands, so `pnpm i` and `pnpm add` now both have `--offline` flag for example.
Also what about code reuse? Yarn npm and pnpm are almost the same clients e.g. generators could be reused for better maintainability. But as far as I understand all CLIs live in isolated files and I can't just create …

[npm | pnpm | yarn]  Improve specs

---

src/docker.ts

Closes #570
From #570:
Remove those two suggestions since there is already a generator for `ps`, and add the common `-d` (or `--detach`) flag to `run`.

fix(docker): Suggestions for `ps` & `-d` option for `run`

---

src/php.ts
src/php/please.ts

Spec addition: Statamic 3's `please` command
Currently `please` is not available.
Add's Statamic 3's `please` spec based on the command list json output
This is replicating the setup of the `artisan` spec for Laravel - perfect fit as Statamic is built on top of Laravel. Full credit to the original authors of the `artisan` implementation for this - this PR operates the same way, but runs the `please` command instead. This includes:
- only adding the spec if `please` is in the current directory, 
- pulls the available options from the `php please list …

feat: add `php please` spec for Statamic 3

---

src/bazel.ts
src/cargo.ts
src/docker.ts
src/fig.ts
src/lerna.ts
src/mask.ts
src/open.ts
src/rails.ts
src/yarn.ts

Fix (ttps://github.com/withfig/autocomplete/pull/619#issuecomment-932371933)
Commands like `ls`, `cat`, etc are often aliased to alternatives like [exa](https://github.com/ogham/exa), [bat](https://github.com/sharkdp/bat), etc. The output and options might not be exactly the same as the native ones, so it can break generators using those commands.
Prepend a `\` before the name of the command to make the shell execute the right binary

fix: Use right binary instead of possible aliased ones

---

src/create-video.ts
src/npx.ts
src/remotion.ts
src/yarn.ts

This PR add [remotion](https://remotion.dev) autocompletion

feat: add remotion autocompletion to fig

---

src/redwood.ts
src/yarn.ts

Feature: add autocompletion for `Redwood`.
Feature: add `create-redwood-app` for yarn create.
No autocompletion for `Redwood`.
Add autocompletion for `Redwood`.
Reference : [RedwoodJS CLI Doc ](https://redwoodjs.com/docs/cli-commands)

feat: add Redwood cli completion spec

---

src/gh.ts

gh pr create does not take any args.
Removed mandatory arg.

[gh] pr create fix

---

src/deno.ts

Spec update
Not up to date.
Updates Deno spec to 1.15 & 1.16. This modernises the spec a bit (sets `requiresEquals` where appropriate) and, because requiresEquals optional arguments are supported now, adds an environment variable generator for `--allow-env`.
Deno 1.16 technically isn't out yet, but will be in less than 24 hours. It doesn't actually introduce anything in the CLI, all the new stuff was in 1.15.
(Still saying it's updated to 1.16 so future-me doesn't get confused when updating to 1.17)
Also, I've been gone for a while for a bunch of …

feat(deno): update spec to 1.16

---

src/git.ts

Fixes #728
Git has a handy alias `git checkout -` that can switch to the previous branch. From the Git 1.6.2 docs:
`* "git checkout -" is a shorthand for "git checkout @{-1}".`
It's not suggested by Fig. Fig suggests I might want `--conflict` instead. But I am feeling `--conflict`-avoidant.
Fig suggests this handy alias, because switching between two branches is great.
https://github.com/git/git/blob/master/Documentation/RelNotes/1.6.2.txt#L85

Add `git checkout -` to git autocomplete

---

src/docker.ts

Bug fix
When you type `docker volume rm`, Fig auto-suggests to use the `-f, --force` flag as expected. However, when you select that option from the autocompletion menu, you get `docker volume rm -f,\ --force` instead of `docker volume rm -f` as expected.
Fig inserts the correct value for the `-f` option: `docker volume rm -f`
\-

fix: -f option definition for docker volume rm

---

src/elm.ts

Feature: Support for [Elm](https://elm-lang.org/)'s cli
Support all of the `elm` cli commands:
- `elm repl`
- `elm init`
- `elm reactor`
- `elm make`
- `elm install`
- `elm bump`
- `elm diff`
- `elm publish`
Includes suggestions for the packages that can be installed as well.
Recording of the install suggestions:
https://user-images.githubusercontent.com/1542461/142098308-65a6b161-d8de-4de3-b187-8499d7ac9c49.mp4

Support for elm cli

---

src/npx.ts
src/remix.ts

Feature add [Remix](https://remix.run/)
No autocomplete for Remix CLI
Add's autocomplete for Remix CLI
[Discord discussion](https://discord.com/channels/837809111248535583/839904572993568820/915308587746725968)

feat: add `Remix` to autocomplete

---

src/create-remix.ts
src/npx.ts

Feature add [create-remix](https://remix.run/)
No autocomplete for `create-remix`
Add autocomplete to `create-remix`

feat: add `create-remix` to autocomplete

---

tsconfig.json

Adds `"DOM"` to the `lib` array in tsconfig.json
Lots of specs use `console` to log information and errors, but because it's part of the DOM API it's a type error because TS hasn't been told that it's valid in this context. It doesn't fail at build time.
Using `console` is no longer a type error, so you can `log` away in peace. Be free from accidentally auto-importing `isConstructorDeclaration`!

Add DOM to tsconfig lib

---

src/cordova.ts

Feature: Add [cordova cli](https://cordova.apache.org/docs/en/10.x/reference/cordova-cli/index.html)
There is no autocompletion for `cordova`
Adds autocomplete functionality for `cordova` cli
Cordova CLI specs can be found [here](https://cordova.apache.org/docs/en/10.x/reference/cordova-cli/index.html)

feat: add cordova completion spec

---

src/git.ts

Bug fix
Fixes #776
When using `git reset ...` subcommand, examine whether the string
includes the `--` before adding it again.

fix(git): correct behavior of treeish with reset

---

src/just.ts

Adds the `just` spec (https://github.com/casey/just)
`just` is a task runner, similar in usage to `make` but focused on running tasks instead of being a build system.
You can create a "justfile" and invoke any amount of "recipes". These recipes can also take arguments (see below).
Relevant issue: withfig/fig#638
TL;DR: Fig doesn't have a way to model this behaviour natively, so it all has to be implemented in a generator. I've gone to great lengths to make things "just work" 😉
Current to-do:

feat: add `just` spec

---

src/git.ts

Feature
Fig doesn't have completion for the `git blame` subcommand.
Fig has great support for the `git blame` subcommand.

Add `git blame` support

---

src/sips.ts

Feature
No autocompletion for the `sips` macOS image manipulation command.
Added support for the `sips` command.

Support macOS `sips` command

---

src/pyenv.ts

Feature
No options are displayed for `pyenv versions`

feat: add options for `pyenv versions`

---

CONTRIBUTING.md

Docs typo.
The link does not exist.
This new link is what the old heading was renamed to.

typo: fix link in CONTRIBUTING.md

---

src/npm.ts
src/yarn.ts

Feature
Fixes #718 
Adds the same npm parser directives to `yarn` and `yarn run` in its completion spec. They're now exported and reused as `npmParserDirectives`.
I didn't see any existing unit tests for these files to add to. Is there more testing you'd like me to commit?

Added npm 'run' parser directives to yarn

---

src/npx.ts
src/vsce.ts

Feature
No support for `vsce`: the vscode extension manager.
Added support for the `vsce` with all the commands and options.

feat: `vsce` support

---

src/xed.ts

This PR adds a spec for the `xed` xcode invocation command.
I checked the [contribution guidelines](https://fig.io/docs/getting-started/contributing) but didn't see any PR template.
For the most part, this is just a rip from the xed man page. Some of the command descriptions were a little more verbose there, so I tried to summarize as best as I could.
Hopefully this works!
Thanks, looking forward to the review 😎
man page:

Add xed spec

---

src/git.ts

Feature
No support for the `git archive` subcommand
Adds support for the `git archive` subcommand

feat: add git archive subcommand

---

.prettierignore

Bug fix
See description https://github.com/withfig/autocomplete/pull/825
Linting no longer fails

Ignore index.d.ts when linting

---

src/checkov.ts

Added autocompletion spec for the open source IaC scanning tool Checkov by Bridgecrew.io
No previous support for this CLI tool.
Support for Checkov!
Fig rocks!

feat: add `checkov` spec

---

src/eb.ts

Feature
It doesn't support all the `eb` commands of AWS
Now fig supports `clone` subcommands and all it's options. Also, `open` subcommand was added
I will be working to add all the commands of `eb`

feat(eb): add `clone` subcommand

---

src/okta.ts

The [Okta CLI](https://cli.okta.com/) is a tool to manage [Okta](https://www.okta.com/) identity management applications & organizations.
Feature
`okta` commands are currently not-supported
Autocomplete and documentation to help guide developers using the `okta` CLI

feat: add Okta CLI spec

---

src/exercism.ts

Feature: Add completion spec for Exercism CLI
Currently, there are no completion options for the `exercism` command.
There will be completion options available for the `exercism` command.
https://exercism.org/docs/using/solving-exercises/working-locally

Add Exercism support

---

src/yank.ts

Feature: add support for the [`yank`](https://github.com/mptre/yank) command line tool.
There is no current behavior.
New behavior is support for the `yank` command line tool.
Please let me know if there are any changes desired by the maintainers.

feat: add yank completion spec

---

src/eb.ts

Feat
It doesn't support all `eb` commands from AWS
Now supports `use` subcommands and all of the options and args
None.

feat(eb): add `use` subcommand

---

src/traceroute.ts

Feature: add support for the `traceroute` command line tool.
There is no current behavior.
New behavior is support for the `traceroute` command line tool.
Please let me know if there are any changes desired by the maintainers.

feat: add traceroute completion spec

---

src/valet.ts

In response to an email.
The `valet link` hostname argument is optional: https://laravel.com/docs/8.x/valet#the-link-command

Set `valet link` argument as optional

---

src/dbt.ts

Docs update - updates the description of a completion spec
dbt appears in uppercase as "DBT".
dbt should appear in lowercase, per [the brand guidelines](https://www.getdbt.com/brand-guidelines/)
Not trying to be pedantic! I am an engineer at dbt Labs, and a huge fan of Fig! Just noticed this in the completion spec and thought I'd propose a quick change!

Lowercase "dbt" in dbt completion spec

---

src/task.ts

New featture: Added the [task - Taskwarrior](https://taskwarrior.org/) completion spec
Task warrior is a **HUGE** command line application to help manage your TODOs in the terminal.  There are lots of filters and modifications and that can be done within Taskwarrior.  This spec is not feature complete with all the filters and modifications but provides a very good start to providing users with many of the most useful and frequently used options.  Additional help would be greatly appreciated and code review to optimize handling filter suggestions and …

feat: add task completion spec

---

src/clang.ts

**What kind of change does this PR introduce? (Bugfix, feature, docs update, ...)**
Feature
No support for `clang`, the C/C++ compiler.
Added support for `clang` and its commands/options.
TBH I didn't write the whole spec, most of it is generated by a parser I wrote to parse the `clang --help` command and produce a spec out of it, then I fixed some issues in the spec and improved it a bit :D if there're any issues make sure to let me know!

Add `clang` support

---

src/brew.ts

it fixes a missing `brew` command: `brew postinstall`.
autocomplete is missing this command
`brew postinstall` is shown in autocomplete 
screenshot of missing command `--help`

feat: add brew command 'postinstall'

---

src/minikube.ts

[Minikube](https://github.com/kubernetes/minikube) implements a local Kubernetes cluster on macOS, Linux, and Windows. 
Feature
`minikube` commands are currently not-supported
Autocomplete and documentation to help guide developers using the `minikube` CLI
This PR resolves this issue #628

feat: add minikube completion spec

---

src/omz.ts

**What kind of change does this PR introduce? (Feature)**
Add a new `reload` option right after `pr`

feat(omz): add reload option

---

README.md

We must use `--cask` to install fig

Readme: Fig is a brew cask formula

---

src/gh.ts

feat: add missing 'gpg-key' gh command
fix: gh repo commands.
gh is missing some `gh repo` commands and `gh gpg-key` command
update and fix the above issues
https://cli.github.com/manual/gh_gpg-key
https://cli.github.com/manual/gh_repo

add missing gh commands.

---

src/cargo.ts

This adds all the remaining subcommands to cargo, thankfully cargo is based on clap 3 which I just recently improved.
What is missing still from cargo spec:
* All the current generators could be improved, most are slow and not get functionally
* Still missing tons of plugins (cargo-outdated, cargo-edit, etc.)

feat(cargo): Add all remaining subcommands

---

package.json
src/gpg.ts

Adds specs for `gpg`.
`gpg` does not have completions #890.
`gpg` does have completions
Adds gpg completions (taken straight from the man page).
Adds two generators, both use `gpg --version` to get supported algorithms

feat(gpg): add completion spec

---

src/rails.ts

bug fix
Currently, the rails completion spec checks if rails is in the Gemfile, if there isn't a gemfile or if rails isn't in it the only completion for rails will be `new`.
The problem, is that it checks for rails using `\grep "gem 'rails'"`. The problem with this is that it only matches when 'single-quotes' are used, if "double-quotes" are used, grep won't match anything and only `new` will be suggested.
Fixes #870
This commit makes it match double and single quotes using `\grep "gem ['\"]rails['\"]"`.

fix: search double quotes in rails dynamic generator

---

tsconfig.json

This should fix issues concerning JS features that are not yet supported by safari or that are not supported by old safari versions.

fix(build): target `ES6`

---

src/twilio.ts

**NOTE:** I'm intentionally leaving out the API subcommand for the initial PR because it's _huge_.
https://user-images.githubusercontent.com/52195359/152804755-d8d91192-dd6b-4252-87ba-e1f351d6d054.mp4
Two necessary pieces of context:
1. The Twilio CLI has "subcommands" but they're all a single colon-separated token. I chose to model this in the spec as nested subcommands.
2. The goal is to build the subcommand token, which means we need to use a generator, but subcommands inherently can't have a "generator".
This spec relies on the behaviour that subcommands have precedence over optional arguments, and arguments can have generators.
The argument generator helps build the subcommand, and once the subcommand is complete, Fig provides the suggestions for args and options.

feat: add twilio CLI

---

src/mkdir.ts

Adds folder completion to the `mkdir` command.
Currently, if I’m at ~ and I’m trying to make a new folder in ~/Desktop/work/, I have to manually type in `mkdir Desktop/work/<folder name>`. There is no autocomplete for “Desktop/work/”.
If I am at ~ and I’m trying to make a new folder in ~/Desktop/work/, I will see my list of folders in the cwd as soon as I type `mkdir `. Then I will be able to autocomplete Desktop/ and same for work/.

feat: update mkdir completion

---

src/git.ts

Bug fix
#901
- Autocomplete ignores '--' in `git diff`.
- Autocomplete only suggests one commit when you can provide as many as 
you want.
- Autocomplete recognises '--' and provides `filepath` suggestions.
- `git diff` now uses `isVariadic` to suggest many arguments.

feat: improve git diff

---

src/checkov.ts

Checkov has new command-line options so those were added to the completion spec
There were a few missing elements for existing options which was fixed (eg. added filepath template to config-file)

feat: update checkov completion spec

---

src/killall.ts

Includes generators for process names and users. Both are not linux-compatible. Listing users uses dscl, process names checks for ".app"
Next up is updating deno to 1.19

feat: add `killall` spec

---

src/touch.ts

Feature.
`touch` has no completion for directories. If I am at ~ and want to create a file at ~/myfolder/newfile, there is no completion for myfolder.
Add `touch` completion, similar to #852.

feat: add `touch` completion

---

src/rmdir.ts

Feature.
`rmdir` has no completion.
Adds completion to `rmdir`.
I initially created a new generator for this that filters out all of the non-empty folders, but using the folders template makes more sense. Using the initial method, we would not get completion for `path1` in `rmdir path1/path2/`.

feat: add rmdir completion

---

src/yarn.ts

2 Features:
- Add `react-native` as a CLI;
- Add the `isCommand` flag to `yarn`
Today, `react-native` is not considered a CLI and thus does not autocomplete. Also, we don't get autocomplete for our `package.json` scripts.
<p align="center">
</p>
And for the script:
```json
"android": "react-native run-android",
```  
<p align="center">
</p>
<p align="center">
</p>

feat(yarn): add `react-native` to CLIs

---

src/okteto.ts

Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
Adds generators for `okteto ns use/delete` and `okteto ctx use/delete`
https://github.com/okteto/okteto/issues/1998
https://user-images.githubusercontent.com/56963264/152126700-1bd8d582-044f-4fe4-b5c7-4b84a72f1373.mov
A couple of questions:
- where do we upload the Okteto logo so that we can use `fig://icon?type=okteto`?
- as seen in the demo, there is a bit of delay showing the namespaces when doing `okteto ns use/delete` - is there a way to do some sort of caching to speed this up?
- is it …

feat(okteto): add generators for `ns` and `ctx`

---

src/ansible-playbook.ts

Bug fix
Old spec incorrectly expects a hostname pattern 
**What is the new behavior?**
New spec autocompletes `.yml` file(s) according to the [official Ansible Docs for the CLI](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html)

feat(ansible-playbook): update generators to use `.yml` files instead of hostname pattern

---

package.json

Changes:
1. upgrade typescript to 4.5.0
2. Use tilde instread of caret when specify typescript dependency, because upgrade typescript minor version will introduce breaking change

chore(deps): bump `typescript` to `4.5.0`

---

src/man.ts

feat(man): add generator and options

---

README.md

Doc update 
updated the readme to include [Tabby](https://tabby.sh) as supported terminal

chore: update terminals in README

---

src/tailwindcss.ts

- bug fix
- current `tailwindcss` icon prop throws 404

fix: tailwindcss icon

---

src/man.ts

The autocomplete engine doesn't re-run generators for different tokens if the argument is the same (only affects variadic args).
`trigger: " "` doesn't work because spaces aren't included in the token unless they're escaped.
`trigger: ""` would work but re-runs the generator on each keystroke. Not great performance.
The best solution I found was to simply make a new argument. _Technically_ this is incorrect, since `man` can take multiple pages to look up, but it's not a big deal since (as far as I know) nobody uses it to do that.
Is there another solution? Would love to implement that instead 🙂

fix(man): update suggestions for new token

---

src/npm.ts

Bug Fix: #758
With this fix, the `-w` or `--workspace` and `-ws` or `--workspaces` flags are displayed correctly

fix(npm): workspace and workspaces flag names

---

src/date.ts

New completion spec
No completion for unix `date` command
Completion for unix `date` command
This basically works. The `date` command has some weird structure so I had to create an argument with two potential options for what it does, and document them both in the same argument object in the spec (see https://github.com/qubist/autocomplete/blob/198754849ded82b92df96a9465710de510556a25/src/date.ts#L72-L78). If anyone knows how to do this differently, I'd be happy to learn and implement it: Ideally, `fig` would decide (like `date` does) which …

feat: add basic `date` completion spec

---

src/mdfind.ts

feature
Completion spec does not exist #940 
Add completion spec
Completion spec for [mdfind](https://ss64.com/osx/mdfind.html)
Basic generator for smart folder option `mdfind -s`

feat: add `mdfind` completion spec

---

README.md

fix: link to themes repository
fix
Link not working
Link working

fix: link to themes repository

---

package.json

Updates package metadata
https://github.com/withfig/autocomplete/issues/993
`npm bugs` from the repo would open the url `https://www.npmjs.com/package/@withfig/autocomplete` in browser
`npm bugs --browser false` will print the following output 
```
@withfig/autocomplete bug list available at the following URL:
https://www.npmjs.com/package/@withfig/autocomplete
```
`npm bugs` from the repo would open the url `https://github.com/withfig/autocomplete/issues` in browser
`npm bugs --browser false` will print the following output 
```
@withfig/autocomplete bug list available …
```

chore: add bugs url to `package.json`

---

src/git.ts

feature
Closes #987 
added a new flag to command: `git tag --points-at`

feat(git): add missing flag to `git tag`

---

src/git.ts

Introduces `apply` subcommand for `git`
`git` does not suggest `apply` subcommand. 
Fixes https://github.com/withfig/autocomplete/issues/998
`git` now suggests `apply` subcommand with the relevant options

feat(git): add `apply` subcommand

---

src/softwareupdate.ts

Feature: New completion spec
CLI request: closes https://github.com/withfig/autocomplete/issues/942
Spec does not exist for `softwareupdate` command 
Adds completion spec for `softwareupdate` command

feat: add `softwareupdate` spec

---

src/npm.ts

Improve completion spec of `npm`
Several commands are incorrectly grouped. Several options are missing
Partially fixes issue: https://github.com/withfig/autocomplete/issues/983
Improves multiple subcommands
NOTE: Though this improves the whole npm spec by adding options to certain subcommands and by grouping aliased subcommands together, this is in no way exhaustive and further improvements would be needed
Follow up of: https://github.com/withfig/autocomplete/pull/1001

feat(npm): improvements

---

src/fig/fig@latest.ts
src/fig/shared.ts

Fixes `internal` subcommand to be properly hidden and aliased

chore(fig): Update spec to B405

---

src/deno.ts
src/deno/config_schema.d.ts
src/deno/deno_doc.d.ts

Adds `deno task` and `deno bench`, improves (and simplifies) the logic for the `deno doc` suggestion generator.
The deno config JSON schema also allows for additional keys. This spec uses the `"fig"` property to customize the:
* Priority
* Display name
* Icon
* Description
* Hidden status
This PR also adds a deno directory with supporting files:
1. Vendored type definitions for deno doc (please let me know if I need to do this differently)
2. Automatically generated types for the config JSON schema
Fig 1. Task suggestions
Fig 2. Example config for the above
Fig 3. `deno doc` suggesting something it couldn't before

feat(deno): update to 1.20, improve doc generator

---

src/deployctl.ts

Adds the spec for `deployctl`, the Deno Deploy command line tool

feat: add `deployctl` spec

---

src/degit.ts
src/npx.ts
src/yarn.ts

Generator only works with plain github user/repo for now but that's all most people ever use anyway

feat: add `degit` spec

---

src/turbo.ts

Adds turbo CLI (turborepo) https://github.com/vercel/turborepo
Currently uses a new icon (very much open to critical feedback on this)
I made a _lot_ of variations, happy to change if necessary. On some of these there are extra transparent pixels, for reasons beyond my comprehension

feat: add `turbo` cli

---

src/yo.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
No user facing change

chore: replace deprecated `String.prototype.substr()`

---

src/cmake.ts
src/exa.ts
src/git.ts
src/go.ts
src/jest.ts
src/kubectl.ts
src/ns.ts
src/rake.ts
src/tar.ts
src/terraform.ts
src/valet.ts
src/wp.ts

Related: https://github.com/withfig/fig/issues/1031
This was a quick regex find-replace, please let me know if I missed anything.

fix: add `{cursor}` to options that insert an `=`

---

src/cosign.ts

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
feature
no support for cosign
will add cosign CLI autocompletion support
https://github.com/sigstore/cosign
https://github.com/sigstore/cosign/pull/1360

feat: add `cosign` autocompletion

---

src/kubectl.ts

Fix kubectl suggestions
The suggestions aren't correct
The suggestions should to be lowercase

fix(kubectl): lowercase some suggestions

---

src/wasm-bindgen.ts

Adds a new spec for the `wasm-bindgen` command-line tool, introduced by the Rust and WebAssembly Working Group for working with bindings between WebAssembly modules and JS.
Fig doesn't show any autocompletion for `wasm-bindgen`.
There is functional autocompletion for the `wasm-bindgen` tool:
Fixes #1072.

feat: add `wasm-bindgen` spec

---

src/wasm-bindgen.ts

UX enhancement to the `--out-name` option in the `wasm-bindgen` CLI tool.
Does not current suggest token.
When the user types a file when passing an `--out-name` flag/option, the user input will be prioritized in the list of autocomplete suggestions by being listed at the very top.
Documentation: https://fig.io/docs/reference/arg#suggestcurrenttoken
Follows-up #1073 (5759ec1), suggestion by @mschrage

[wasm-bindgen] suggest current token for `--out-name` option

---

src/tccutil.ts

Not that this matters much since if you need to use `tccutil` Fig probably isn't working, but it's a fun and small spec!
Getting a list of bundle IDs is a surprisingly difficult task... I'll reuse this generator for `open -b`

feat: add `tccutil` spec

---

src/mix.ts

Improve option suggestions for the `mix run` command based off [Mix run documentation](https://hexdocs.pm/mix/1.12/Mix.Tasks.Run.html#module-command-line-options).
Fig does not suggest any options for the `mix run` command.
**What is the new behavior?**
Fig will suggest options like:
- `mix run --no-halt`
- `mix run --no-deps-check` 
- [Documentation with the options the run subcommand can take](https://hexdocs.pm/mix/1.12/Mix.Tasks.Run.html#module-command-line-options).

feat(mix): add options for `mix run`

---

src/open.ts
src/tccutil.ts

`open -a` now lists all apps on your system - this is surprisingly fast. `open` can open all of these, not just apps in /Applications or ~/Applications
Adds completions for `open -b`. This is surprisingly slow. Moved generator from tccutil

feat(open): improve generators

---

src/checkov.ts

`--bc_api_key` to `--bc-api-key`
Bug fix
For checkov, Fig suggests `--bc_api_key`
Should suggest `--bc-api-key`

fix(checkov): replace underscore from options

---

src/robot.ts

Feature - new generator for `robot spec`
Currently there is no generator for suggesting test cases
Now there is a generator for suggesting test cases from `.robot` files

feat(robot): add generators

---

src/goreleaser.ts

This PR adds the spec for goreleaser and fixes #1095 
-
-
-

feat: add goreleaser spec

---

src/valet.ts

This PR adds 6 new commands for the new Laravel Valet https://laravel.com/docs/9.x/valet isolation feature.
You can see these new commands on this PR: https://github.com/laravel/valet/pull/1216 and in this tweet from Matt Stauffer https://twitter.com/stauffermatt/status/1510634227360210950
New commands list:
- valet isolate php@XX
- valet unisolate
- valet isolated
- valet php
- valet composer
- valet which-php
Commands missing.
New isolation commands available.

feat(valet): add isolation subcommands

---

src/brew.ts

I added ```brew reinstall``` because I use it pretty often and it was missing. All it does is install and reinstall. Similar to ```brew upgrade``` but simpler.
See here for more info
https://docs.brew.sh/Manpage#reinstall-options-formulacask-

feat(brew): add `reinstall` subcommand

---

src/git.ts

Shows commands found on your $PATH  in the list of subcommands. These commands can also be supported explicitly in the `optionalCommands` array, to add options and arguments. Currently this only supports `git-open`, `git-recent`, and `git-flow` but it's easy to add more.

feat(git): support `git-xyz` commands on $PATH

---

src/git.ts

Scraped from the manual page. Descriptions need to be cleaned up still.
Because of Fig's UI and {cursor} support, this is actually **better than fish completions** for git-config (which are often incorrect and slow down the whole shell)

feat(git): add config key suggestions

---

src/valet.ts

Fix
Fixes #1123 
Make commands' whose arguments aren't required optional.
I'm not familiar with Laravel Valet so I looked at the commands [here](https://laravel.com/docs/9.x/valet#other-valet-commands). Let me know if I missed anything/made any mistakes.

fix: Add isOptional to arguments that needed them

---

src/git.ts

Bug fix
When the user types `git log `, fig suggests the autocompletion `--p`, which results in the error `fatal: unrecognized argument: --p`. Per the [git docs](https://git-scm.com/docs/git-log#_diff_formatting), the available options for `git log` to generate a patch are `-p`, `-u`, and `--patch`.
To display the correct options.

fix(git): correct `log` option

---

src/deno.ts
src/deno/generators.ts

Fun fact I learned while checking the logic: deno will happily delete itself if it's installed to the same location it installs scripts (which, by default, it is)... shooting yourself in the foot is just a `deno uninstall deno` away!

feat(deno): add `uninstall` generator

---

src/hexo.ts

feature: autocomplete for `hexo-cli` for [Hexo](https://hexo.io)
does not provide autocomplete for hexo-cli
provides autocomplete for hexo-cli commands

feat: add `hexo` completion spec

---

src/typeorm.ts

Fix
TypeORM version 0.3.0 removes `migrations:*` commands. ([Release 0.3.0 · typeorm/typeorm](https://github.com/typeorm/typeorm/releases/tag/0.3.0))
Don't show the removed commands

fix(typeorm): remove migrations subcommands

---

src/dotenv.ts

feature: add completion spec for [dotenv](https://github.com/bkeepers/dotenv)
does not provide autocomplete for dotenv commands
provides autocomplete for dotenv commands

feat: add dotenv completion spec

---

src/scp.ts
src/ssh.ts

Currently the signature for `scp` is wrong. Like `cp`, it can also take _multiple_ sources and copy to a single destination.

feat(scp): add hosts and filepaths completions

---

src/-.ts
src/..ts
src/export.ts
src/nocorrect.ts
src/noglob.ts

This should be merged before https://github.com/withfig/public-site-nextjs/pull/127
These commands will be hidden from the manual, but still accessible.
Sidenote: It's so nice to be back on my _actual_ dev machine instead of my girlfriend's laptop. Back to vim!! 🚀

feat: hide shell syntax commands

---

src/yarn.ts

Bug fix
Running `yarn workspace` returns no workspace
It now returns workspaces normally
This is a follow-up to #1141  in which I did not clean up the output of the `workspace info` command
This is the output you get running `yarn workspaces info` in yarn 1.22.18.
```log
yarn workspaces v1.22.18
{
"storybook": {
"location": "storybook/intro",
"workspaceDependencies": [],
"mismatchedWorkspaceDependencies": []
},
"storybook-vue": {
"location": "storybook/vue",
"workspaceDependencies": [],
"mismatchedWorkspaceDependencies": []
}
}
✨  Done in 0.03s.
```

fix(yarn): correct workspace parsing for 1.x.x

---

src/mob.ts

Add completion spec for "mob"
"mob" offers fast git handover for remote collaboration, see https://mob.sh/
Signed-off-by: Thomas Much <github@snailshell.de>

feat: add mob completion spec

---

src/pm2.ts

bug fix
selecting the help option from pm2 will resolve ton `-h,--help`
resolve help to `-h`

fix(pm2): separate help flags

---

src/flyctl.ts

Added completion specs for [flyctl](https://fly.io/docs/flyctl/) CLI, the command-line interface for fly.io! 
It is auto-generated with the [`github.com/withfig/autocomplete-tools/packages/cobra`](https://github.com/withfig/autocomplete-tools/blob/main/packages/cobra/README.md) package. With the help of amazing @davidalpert we found a work-around and made the package to work with the current [`flyctl` cobra implementation](https://github.com/superfly/flyctl). You can see the implementation here https://github.com/BogDAAAMN/flyctl/commit/c0f338a6f3c59acc8286a8c82836fc2e73124b6f.
I am not familiar enough with Go to propose a better implementation or perhaps a GitHub Action, although I would love to try …

feat: add flyctl spec

---

src/fly.ts

In addition to #1202, adding completion spec for `fly` command, alias of `flyctl`. Suggested by @jsierles. 
I propose we leave it like this until `flyctl` transitions to `fly`.
> Note: Most installations of `flyctl` also alias `flyctl` to `fly` as a command name and **this will become the default name in the future**. During the transition, note that where you see `flyctl` as a command it can be replaced with `fly`.
Source: https://github.com/superfly/flyctl

feat: add completion spec for `fly` (alias of `flyctl`)

---

src/git.ts

feature?
`git` autocompletions do not include the `daemon` command
`git daemon` is now supported*
~I’m not sure how to implement this, but several `git-daemon` options (including `--base-path`) require that they be specified as `--base-path=value` rather than `--base-path value`. Is there a way to tell Fig to insert an `=` instead of a space?~ That’s the `requiresEquals` option, will push an update shortly.

feat(git): add `git-daemon` subcommand

---

.all-contributorsrc
src/mob.ts

Updates the "mob" completion spec with frequently used, but undocumented abbreviations of some subcommands.

feat(mob): add subcommands aliases

---

src/hugo.ts

Bug fix
Fixes: #1213 
No
Remove archetype file extensions in --kind option hints

fix(hugo): remove archetype file extension in --kind option

---

src/deno.ts
src/deno/generators.ts

This uses the completions generated by `deno completions fig`, which should make it easier to switch to automatic PRs in the future if we go down that route with it. Even if not, this _massively_ simplifies the amount of work it'll be to update the deno spec.
Because it's generated by the CLI itself it's missing some quality of life stuff that I've manually added to it over the last 8 months, when it's added back in I'll mark the PR as ready.

feat(deno): update to 1.22

---

src/remotion.ts

Update Remotion completions with new commands, flags and Remotion Lambda feature
Represents the capability of Remotion 2.0 while 3.0 is out now
Represents 3.0 functionality

Update Remotion completions for 3.0

---

src/nl.ts

New completion
There is no completion for `nl`
There will be completion for `nl`
`bash
❯ nl --fake-argument
nl: illegal option -- -
usage: nl [-p] [-b type] [-d delim] [-f type] [-h type] [-i incr] [-l num]
[-n format] [-s sep] [-v startnum] [-w width] [file]
```

feat(nl): add completion

---

src/tac.ts

New completion
There is no completion for `tac`
There will be completion for `tac`
```bash
tac --help
Usage: tac [OPTION]... [FILE]...
Write each FILE to standard output, last line first.
With no FILE, or when FILE is -, read standard input.
Mandatory arguments to long options are mandatory for short options too.
-b, --before             attach the separator before instead of after
-r, --regex              interpret the separator as a regular expression
-s, --separator=STRING   use STRING as the separator instead of newline
--help        display this …
```

feat(tac): add completion

---

src/create-next-app.ts

Latest `create-next-app` includes these options:
```
Usage: create-next-app <project-directory> [options]
Options:
-V, --version                      output the version number
--ts, --typescript
Initialize as a TypeScript project.
--use-npm
Explicitly tell the CLI to bootstrap the app using npm
--use-pnpm
Explicitly tell the CLI to bootstrap the app using pnpm
-e, --example [name]|[github-url]
An example to bootstrap the app with. You can use an example name
from the official Next.js repo or a GitHub URL. The URL can use
any branch and/or subdirectory
--example-path <path-to-example>
In a rare case, your GitHub URL might contain a branch name with
a slash (e.g. bug/fix-1) and the path to the example (e.g. foo/bar).
In this case, you must specify the path to the example separately: …
```

feat(create-next-app): add `use-pnpm` and `version` options

---

src/base32.ts
src/base64.ts
src/basenc.ts

New completions
There is no completion for `basenc`, `base32`, and `base64`
There will be completion for `basenc`, `base32`, and `base64`
`man basenc`, `man base32`, and `man base64`

feat(basenc,base32,base64): add completion

---

src/railway.ts

Update options for some commands, and add `down` and `shell` completion.
No completion for `down` and `shell` commands, and `-s` or `--service` options.
Completion for `down` and `shell` commands, and `-s` or `--service` options.

feat(railway): update options and subcommands

---

src/youtube-dl.ts

bug fix
The argument of youtube-dl "--embed-thumbnails" is incorrect.
It should be changed to "--embed-thumbnail".
youtube-dl now prompts "--embed-thumbnail" correctly.

fix(youtube-dl): correct option name

---

src/op.ts

Adds 1Password CLI completions
This spec is [generated by a ~~very scuffed~~ script](https://gist.github.com/SeparateRecords/1e73dd825bbc0724d930da2d3bbdff0e). Icons, suggestions, templates, and generators are added by hand

feat: add `op` completions

---

src/split.ts

New completion
There is no completion for `split`
There will be completion for `split`
`man split`

feat(split): add completion

---

src/paste.ts

New completion
There is no completion for `paste`
There will be completion for `paste`
`man paste`

feat(paste): add completion

---

src/basename.ts
src/dirname.ts

New completions
There is no completion for `basename` and `dirname`
There will be completion for `basename` and `dirname`
`man basename`

feat(`basename`,`dirname`): add completion

---

src/readlink.ts
src/stat.ts

New completions
There are no completions for `stat` and `readlink`
There will be completions for `stat` and `readlink`
`man stat`

feat(`stat`,`readlink`): add completion

---

src/nx.ts

Fixed issue where the NX App generator wasn't detecting any apps from the workspace.json.
In the current version, there is a filter that wasn't functioning properly and always returning false.
I replaced it with a directly specified null check since the types are already being checked with typescript. My updated code now returns all the apps correctly.

fix(nx): app generator returning no apps

---

README.md

Fix the text from "MacOS" to "macOS".
Spell fix: "macOS"
The text in the question, "Does Fig work on Windows or Linux?", is "macOS".
Change to "macOS".
None

docs: fix typo (MacOS -> macOS)

---

src/npx.ts

Adds pod-install command to npx command (https://github.com/expo/expo-cli/tree/main/packages/pod-install)
npx pod-install is not suggested

feat(npx): add `pod-install` to suggestions

---

src/ng.ts
src/webpack.ts

- Remove unused import/code from `webpack` spec
- Lint `ng` spec

fix: linting

---

src/z.ts

Fixes #1328
`zoxide` users usually have `z` aliased as `cd`. It currently autocomplete only optional flags.
Added folders autocomplete.

feat(z): provide folders autocomplete

---

src/ruby.ts

This PR is just a grammatical error fix.
No issues created yet because this seems a very tiny thing.
You can see like below that this is correct description.
For your information, the Ruby man says like below.
https://github.com/ruby/ruby/blob/067a5f1a0024ebd270f363cd440147da9dc176b5/man/ruby.1#L212-L213

fix(ruby): update a description to be grammatically correct

---

src/watson.ts

Bug fix/tiny feature correction: args for `watson restart` should be optional.
Typing `watson restart` and enter adds a space and brings up autocomplete with a list of frames.
Typing `watson restart` and enter runs the command. This restarts the last frame.
Typing `watson restart` followed by a space brings up autocomplete with the list of frames.

Make args optional for `watson restart`

---

src/gh.ts

feature
`gh` command `browse` is not supported with autocomplete
`gh` command `browse` will be an option
`gh browse` documentation https://cli.github.com/manual/gh_browse

feat(gh): add browse core command

---

src/st2.ts

Bugfix; fixes #1361.
The `rule-enforcemnt` subcommand is misspelled.
The `rule-enforcement` subcommand will not be misspelled.
N/A

Fix `rule-enforcement` typo

---

src/remotion.ts

For Remotion CLI, adding flags that we recently introduced:
- `--concurrency-per-lambda` flag
- `--quiet` flag
- `--number-of-gif-loops` and `--every-nth-frame` flag
- The output name parameter is now optional.
My plan is to always batch together a few changes and send them from time to time!

feat(remotion): update autocomplete for 3.1

---

src/glow.ts

1. I wanted to add the 'wrapwidth' option to neovim. The suggestion has been open for _**six years**_ nobody has added the option to soft wrap at a set column number.
2. To do that, I had to read the documentation on how to build it.
3. To read the documentation, I wanted to use `glow`.
4. In the documentation was a link that was wrapping over two lines, so I couldn't click it.
5. I wanted to see if there was a flag for glow to use the proper escape codes to make the link clickable.
6. There were no fig completions for glow.
So here we are... I _was_ going to add an option to neovim...

feat: add `glow` completions

---

src/git.ts
src/npm.ts

This does not affect `npm` since the scripts are only visible with `npm run`, but it improves the usability of `yarn` because the scripts are at the top

feat(yarn): bump priority of scripts

---

src/git.ts

Fixes: #1216 
Bug fix and autocomplete branch name in `git-reset` commit object.
`git-reset` is only autocompleted commit hash and `HEAD`.
`git-reset` is autocompletedd commit hash and `HEAD` and local/remote branches.
According to spec, `git-reset` can get `<commit>` https://git-scm.com/docs/git-reset, and `<commit>` indicates git commit object (FYI: https://git-scm.com/docs/git#Documentation/git.txt-ltcommitgt), and branch is just a pointer to the git commit object, so `git-reset` should be autocompleted also with branch names. 
> A branch in Git is …

Fix(git): autocomplete branch name in git-reset

---

src/git.ts

Rel: #1392 
autocomplete branch name in `git-diff` commit object.
`git-diff` is only autocompleted commit hash and HEAD.
`git-diff` is autocompletedd commit hash and HEAD and local/remote branches.
I found out in #1392 that according to the specification `<commit>` includes git branch because git branch is just a pointer of git’s commit object. So fig can autocomplete git’s branch name with a part of `git-` command  same as #1392 `git-reset`. Of course, I do not think fig should autocomplete git’s branch name with all of `git-` command which get …

fix(git): autocomplete branch name in git-diff

---

.npmrc

Small change but quite helpful. When I am installing dependencies via `pnpm i`, it fails and says there are unmet peer dependencies.
<details>
<summary>Full error</summary>
<br>
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
.
├─┬ @typescript-eslint/eslint-plugin
│ └── ✕ missing peer @typescript-eslint/parser@^5.0.0
└─┬ danger
└─┬ @octokit/rest
└─┬ @octokit/plugin-request-log
└── ✕ missing peer @octokit/core@>=3
Peer dependencies that should be installed:
@octokit/core@>=3                 @typescript-eslint/parser@^5.0.0  
hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file …
```

Auto install peer dependencies

---

src/neofetch.ts

feat: add `neofetch` spec

---

src/vercel.ts

Bug fix
#1430
- removes deprecated 'type' arg in `vercel env rm`
- lowercases environment suggestions in `vercel env add` and `vercel env rm`
See #1430 for detailed screenshots and relevant vercel blobs

fix(vercel): Update env spec suggestions (#1430)

---

src/lsblk.ts

Feature
Autocompletion for lsblk is currently not available. Closes https://github.com/withfig/autocomplete/issues/1405 
Adds autocompletion for lsblk
This is my first contribution so feel free to point out any errors☺️

feat: add lsblk spec

---

src/coda.ts

Feature: Add [Coda SDK](https://coda.io/packs/build/latest/guides/development/cli/#create-pack-definition) autocomplete spec.
No Coda SDK spec
New Coda SDK spec added
[Coda](https://coda.io/about) is a new kind of doc that brings words, data, and teams together. It comes with a set of building blocks that anyone can combine to create a doc as powerful as an app.
With a growing dev community, Coda SDK is becoming more popular than ever. This new spec will make Fig an easy choice for Coda Pack developers!

feat: add `coda` spec

---

src/firefox.ts

I was messing around a bit and accidentally discovered that there's a Firefox CLI. Huh. Here's a spec for it.
Only a draft because of one thing: how should I do options for the `--start-debugger-server`? The options are `[ <port> | <path> ]`, but I don't see any way to use something like `exclusiveOn` for arguments. This has got to have come up before, right?

feat: add `firefox` spec

---

src/fdisk.ts

Feature
Autocompletion for fdisk is currently not available. Closes https://github.com/withfig/autocomplete/issues/1407
Adds autocompletion for fdisk

feat: add `fdisk` spec

---

src/tsx.ts

Feature: adds spec for [`tsx`](https://github.com/esbuild-kit/tsx)
There is no autocomplete tool, that I am aware of, for the `tsx` CLI.
This pull request adds autocompletion for all command line options that `tsx` accepts.

feat: add tsx completion spec

---

src/cap.ts
src/capacitor.ts
src/npx.ts
src/yarn.ts

feature
n/a
Adds a new spec for [capacitor](https://capacitorjs.com/docs/cli)
I also added a `cap.ts` spec file because the capacitor CLI can be used either with `capacitor` or `cap` ([Reference](https://github.com/ionic-team/capacitor/blob/22c2fb505ee80dfce335c05f841ffafd21b7842c/cli/package.json#L34)). I was not sure if this is ok or if there is a better way of doing this. If you prefer not to have the second spec I can remove it again.

feat: add capacitor completion spec

---

src/ssh.ts

Spec update for `ssh`
If `~/.ssh/config` file includes `Include` statement - fig doesn't provide suggestion from the included file [Bug: closes #1187]
The `ssh` spec now suggests hosts that are defined in config file included from the `~/.ssh/config` file
Solves this case (`customer-main-site` will be suggested as a host for `ssh ` command
`~/.ssh/config`:
```
Host my-personal-site
HostName 172.0.0.1
User siteuser
Include config.d/*
```
`~/.ssh/config.d/customer`:
```
Host customer-main-site
HostName ...
User blabla
```
This PR also resolves #1450 …

feat(ssh): suggest hosts from `Include`d config files

---

src/typos.ts

[Typos](https://github.com/crate-ci/typos) is a wildly fast code spell-checker, _way_ faster than cspell - it's basically instant on our monorepo. I upstreamed some of our typos to its dictionary and realized we don't have a spec for it yet.

feat: add `typos` completions

---

package.json
src/c++.ts
src/clang++.ts
src/clang.ts
src/g++.ts
src/gcc.ts

Feature
Completion for `clang++`, `c++` (same as `clang`) and `g++` (same as `gcc`)

feat: add specs for c++ compilers

---

src/xcodes.ts

Adds completion spec for [xcodes](https://github.com/RobotsAndPencils/xcodes) CLI.
n/a
Fig will show completions for `xcodes` CLI 
n/a

feat: add `xcodes` completion spec

---

src/npx.ts
src/stencil.ts

feature
n/a
Adds a new spec for [stencil](https://stenciljs.com/docs/cli)
Is there a way to configure, that at least one options is required? The `test` command need either the `--spec` or `--e2e` option.

feat: add stencil completion spec

---

src/man.ts

Can do this a couple of different ways. Currently the cache will be cleared when the generator is next used (lazily). We can also use `setTimeout` to proactively clear the cache after an hour, which may have memory benefits but idk if there are any drawbacks. Will experiment

feat(man): increase cache TTL

---

src/nvim.ts
src/vim.ts

`suggestCurrentToken` for {n,}vim args was added because someone asked for it, but it's actually _much_ more annoying this way. This PR removes it.
Maybe we should have a way to indicate preference for `suggestCurrentToken` in editor args?
```
fig settings spec.vim.suggestCurrentToken true
fig settings spec.nvim.suggestCurrentToken true
```
And in the args:
```
{
suggestCurrentToken: "spec.nvim.suggestCurrentToken",
}
```

feat(vim): remove suggestCurrentToken

---

src/nextflow.ts

Fix
Fig won't help the user when s/he wants to use `nextflow log` to a run name
without specifying one of the options: -but/-before/-after
Both the log subcommand and its options -but/-before/-after
accept a run name as argument. If the user provides a run name
both for the log subcommand and its other options, it's fine,
nextflow knows what to do.
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>

feat(nextflow): Add runname generator for log subcommand

---

src/ddev.ts

Spec addition: `ddev` for the [DDEV](https://ddev.com/) local development environment
Currently `ddev` is not available
Adds the `ddev` spec
Leverages the Fig-provided Cobra module for generating the spec directly from the `ddev` command: https://github.com/drud/ddev/pull/4216

feat: Add ddev spec for DDEV

---

package.json

This fixes a bug with the `infracost` spec.
Currently, the spec imports the `semver` package, but it is not listed as a dependency. This causes errors when using pnpm.
`semver` is added as a dependency in `package.json`.
Fixes #1516

chore: clarify semver as dependency

---

src/sqlfluff.ts

Adds a spec for [sqlfluff](https://docs.sqlfluff.com/en/stable/index.html).
All documentation for subcommands and there arguments has been taken from [sqlfluff's CLI reference](https://docs.sqlfluff.com/en/stable/index.html).
I was able to check and test out everything from the fig-bot checklist locally, however seemed to keep running into this error whilst trying to make any commits:
I wanted to confirm if there was any issues if I pushed the actual commits, and did so with the `-n` flag. But I would appreciate any guidance on how to navigate that error for any future contributions.
Thank you very much in advance!
> Hello @anubhavsharma515, thank you very much for creating a Pull …

feat(sqlfluff): Add spec for sqlfluff

---

src/pip.ts

This PR adds handling of -r / --requirements to pip (and pip3) install subcommand 
Currently pip install gives a list of packages to install but doesn't handle the -r/--requirements option.
`pip install -r` or `pip install --requirements` will give now give return the file list for autocomplete.
I'm not sure why there's so much code commented out under pip install. I've made the minimum change to make my immediate life easier 😄

feat: requirements handling for pip

---

src/gh.ts

Adds support for completions for gh aliases

feat(gh): Add completion for aliases

---

CONTRIBUTING.md

Adds guidelines for hacktoberfest contributions
To discourage tiny typo/grammar fixes, insignificant changes will be marked as `hacktoberfest-invalid`. This will not mark the account as spammy or punish the submitter, but _will_ disqualify the PR from Hacktoberfest (so there's no incentive to do this other than for the good of the project)

docs: Update CONTRIBUTING.md for Hacktoberfest

---

src/gh.ts

The PR adds missing options to various `gh repo` subcommands, and updates a few which were removed/deprecated.
The `gh repo` spec is missing many options in its various subcommands.
Following options have been added:
**New subcommands:**
- `deploy-key`
**New options:**
- `clone`
- `-u`, `--upstream-remote-name`
- `--`
- `create`
- `-c`, `--clone`
- `--enable-issues` --> `--disable-issues`
- `--enable-wiki` --> `--disable-wiki`
- `-g`, `--gitignore`
- `-l`, `--license`
- `-r`, `--remote`
- `-s`, `--source`
- `-t`, `--team`
- `--include-all-brances`
- `--push`
- …

feat(gh): add missing `gh repo` completions

---

src/echo.ts

Feature: Generate args for environment variables on the users system.
Fig currently only returns -n, -e and -E as options for the echo command.
Displays an arg for each environment currently contained on the system

feat(echo): add environment variable generator

---

src/ssh-keygen.ts

Adds missing completion specs.
Currently missing completion specs for `ssh-keygen` command. Closes #1535.
Implement specs for `ssh-keygen`
See `man ssh-keygen`
First time contributing during Hacktoberfest.

feat(ssh-keygen): add completion spec

---

src/dscl.ts

Adds missing completion specs.
Missing completion specs for the `dscl` command.
Adds the `dscl` command specs.
Closes #1545

feat(dscl): Add completion specs

---

src/whereis.ts

adds a completion spec for whereis 
fixes #1529 
no spec for whereis
completion for whereis, no generator for main argument
NA

feat(whereis): add completion spec

---

src/which.ts

Feature
Currently which only suggests the -s and -a options
Suggests names of programs located in $PATH variable when running the "which" command ([issue that suggested this feature](https://github.com/withfig/autocomplete/issues/1527))

feat(which): add generator to pull executables from $PATH

---

src/goreleaser.ts

feat(goreleaser): update spec

---

src/login.ts

Add completion spec for `login` command
Based off [Ubuntu manpage](https://manpages.ubuntu.com/manpages/jammy/en/man1/login.1.html), potentially other OS have additional syntax and this won't work?
Closes #1537

feat(login): Add completion spec

---

src/z.ts

Feature
The current behavior is that z only shows the paths in the current folder. 
The PR changes the z completion to take into account the directories cached by z and the weighting that z provides them. Now you will be able to see all the possible paths that z can take you.

feat(z): add z cache results to completion

---

src/code.ts

Motivated by missing `-` option.
See also:
https://github.com/microsoft/vscode/blob/main/src/vs/platform/environment/node/argv.ts
Complete.
https://github.com/microsoft/vscode/blob/main/cli/src/commands/args.rs
Missing `profile`, maybe more.
https://github.com/microsoft/vscode/blob/main/resources/completions/zsh/_code
Missing `profile`, maybe more.
_(I'll open a PR on `microsoft/vscode` about those later)_
```
>code -v
1.71.2
```

feat(code): add missing flags

---

src/yarn.ts

This addresses the changes in https://github.com/withfig/autocomplete/issues/1285
the yarn command has more options for the `yarn version` command so here I did:
`yarn version -h` then added all the options that were present that had to do with version.
The current behavior is that it only shows `--major/minor/patch`
Now we show in addition to major/minor/patch:
message, premajor, preminor, prepatch, prerelease, preid, no-git-tag-version, no-commit-hooks, access, tag
Also, I added commonOptions, because I saw those were present as well with the `yarn version -h` command

feat: update yarn completion spec

---

src/authchanger.ts

Feature: Autocomplete support for authchanger binary from Jamf Connect
authchanger is a commandline tool for interacting with macOS's authorization database. It's included as a part of the Jamf Connect product

feat: add spec for Jamf Connect authchanger

---

src/yarn.ts

Adding more specs to yarn
**Important**
This is a code solution submitted  for Closes #1611

feat(yarn): add options

---

src/dscacheutil.ts

closes #1553 
dscacheutil spec
Not implemented
1. For the -q subcommand, we can improve -a arg suggestions if we can pass in the value passed to -q. Is this possible right now?
2. There seems to be a bug with the -buckets and -entries options in -cachedump since the name of those options are more than 1 character long (excluding the dash), chaining multiple don't work. See the gif below

feat: dscacheutil spec

---

src/multipass.ts

- New spec
- Fig does not autocomplete this tool
- Add new spec for multipass ubuntu cli (https://multipass.run/)
TODO:

feat: add spec for multipass

---

src/fig/shared.ts

`fig theme --list` has been in the CLI a sufficient enough time (months) and will help migrate to Fig v2s new location for the theme folder

feat(fig): use fig internal command to list themes

---

src/pytest.ts

Add spec file for pytest cli
The [pytest](https://docs.pytest.org/en/7.1.x/) framework makes it easy to write small, readable tests, and can scale to support complex functional testing for applications and libraries.

feat: Add `pytest` spec

---

src/brew.ts

Now the completions show formulae and casks from all the repos, not just the default ones
Feature
Doesn't contain formulae and casks from all the user installed taps
Now it does :)

feat(brew): add better generators for casks and formulae

---

src/mdls.ts

- New spec
- Resolves #1548 
- Add new `mdls` spec
```
MDLS(1)                   BSD General Commands Manual                  MDLS(1)
NAME
mdls -- lists the metadata attributes for the specified file
SYNOPSIS
mdls [-name attributeName] [-raw [-nullMarker markerString]] file ...
DESCRIPTION
The mdls command prints the values of all the metadata attributes associated with the files pro-
vided as an argument.
The following options are available:
-name        Print only the matching metadata attribute value.  Can be used multiple times.
-raw         Print …
```

feat: add spec for `mdls`

---

src/rsync.ts

- Update `rsync` spec to add generators for SRC and DEST
- No generators
- Now fig suggest ssh hosts and files

feat(rsync): add generators

---

src/br.ts
src/broot.ts

New spec for `broot`
Missing spec for `broot` (closes https://github.com/withfig/autocomplete/issues/1526)
Add spec for `broot`
- Ran `npm run test` and `npm run lint:fix` before raising PR
- Tested this spec locally, autocomplete is working correctly

feat(broot): add broot spec

---

src/pkg-config.ts

Feature: initial completions for [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/)
This fixes #1530.
Completions for `pkg-config` are now available.
None

feat(pkg-config): add spec

---

src/aws.ts

In this commit, we want to make it so aws --profile auto completes
with the list of profiles you have available.
Currently the aws command doesn't know about --profiles
Generally these profiles live inside a credentials file
but instead of directly looking at the credentials file,
we ask aws to give us a list of the profiles using
`aws configure list-profiles`
closes #542

feat(aws): add `--profile` option support

---

src/nextflow.ts

- feat(nextflow): Add secrets command and generator
It adds autocomplete for the new secrets command, and a generator for its args.
There is no autocomplete for the secrets command.

feat(nextflow): add secrets command and generator

---

src/launchctl.ts

This is a basic implementation of launchctl.
We don't want to attempt to list the launchctl labels or service targets.  That can be a future exercise.
Feature
Currently autocomplete doesn't support launchctl
Now launchctl is supported

feat: add launchctl completion spec.

---

src/git.ts

fix: cherry-pick declared options as subcommands

---

src/brew.ts

Feature that adds `brew home` command autocomplete.
As for now there is no autocomplete for such command.

feat(brew): add `home` subcommand

---

src/brew.ts

1. added `rm` and `remove` synonyms for `uninstall` subcommand;
3. `abv` and `info` were separated into subcommands though did the same so I joined them;
5. default description for `—help` option were `Show this message` which didn't make sense so I changed it to more sensible `Show help message`.

feat(brew): aliases and fixes for `uninstall`, `abv` and `info`

---

src/kubectl.ts

feature
there is no `--namespace` global options
add a `--namespce` global command-line options, see `kubectl options` for all global options for kubectl
N/A

spec(kubectl): add --namespce global command-line options

---

src/curl.ts

Feature
Resolves #1680 (the completion spec for `curl` is missing several options).
The missing options are added.

feat(curl): add missing options

---

src/ls.ts

fix: add missing flags to ls

---

src/bcd.ts

Usage: bcd [OPTIONS] [BOOKMARK]
Arguments:
[BOOKMARK]  Bookmarked directory to change to
Options:
-s, --store <STORE>    Store the current directory as a bookmark STORE
-r, --remove <REMOVE>  Remove a specified bookmark REMOVE
-l, --list             List the stored bookmarks
-V, --version          Print version information
-h, --help             Print help information command from https://bcd.noser.net
new application support
N/A
Support for `bcd` command line tool
File automatically generated using `clap_complete_fig` as a part of the build.

feat: add bcd spec

---

src/taplo.ts

Fixes https://github.com/withfig/autocomplete/issues/1532 
The completion spec does not exist for taplo 
autocomplete will be supported for taplo 
I used `taplo --help` as reference to work with all the subcommands and options. Also used the 
`taplo <subcommand> --help` which produces different manual for each corresponding subcommands and option(s) in taplo.
Autocompletion for `taplo` in action;

feat: add taplo completion spec

---

src/gt.ts

Adds completion spec for `gt` cli (CLI of [graphite.dev](https://graphite.dev/))
Currently there is no autocomplete for the `gt` cli 
Now there is autocomplete for the `gt` cli 😉

feat: add gt (graphite.dev CLI) completion spec

---

src/nextflow.ts

- feat(nextflow): Fix stub-run option typo
It fixes a typo in the -stub-run option for the run command.
The autocomplete is incorrect due to a typo.
The autocomplete works as expected.

fix(nextflow): `stub-run` option typo

---

src/kafkactl.ts

New autocomplete spec for [`kafkactl`](https://github.com/deviceinsight/kafkactl)
No autocomplete
Autocomplete
Generated with the cobra integration
```diff
diff --git a/cmd/root.go b/cmd/root.go
index 8338d38..d14f459 100644
--- a/cmd/root.go
+++ b/cmd/root.go
@@ -7,6 +7,7 @@ import (
"strings"
"github.com/deviceinsight/kafkactl/internal/env"
+	cobracompletefig "github.com/withfig/autocomplete-tools/integrations/cobra"
"github.com/deviceinsight/kafkactl/cmd/alter"
"github.com/deviceinsight/kafkactl/cmd/attach"
@@ -57,6 +58,7 @@ func …
```

feat: add spec for `kafkactl`

---

src/hyperfine.ts

Fixes https://github.com/withfig/autocomplete/issues/1549 to add new autocompletion spec for `hyperfine`
Currently, fig does not have support to autocomplete hyperfine
Autocomplete for `hyperfine`
First contribution to Fig :)
I have read the CLA Document and I hereby sign the CLA

feat: add hyperfine completion spec

---

src/remotion.ts

We periodically send a PR with all the new options added to Remotion. Incomplete list of new options:
- `--height` and `--width` flags
- `npx remotion install` commands
- `--number-of-shared-audio-tags` flag
- `npx remotion lambda compositions` command
- `--webpack-poll` flag
- `--enable-extensions`

feat(remotion): add new flags

---

src/pnpm.ts

- Support option `-C <path>, --dir <path>` close #1734
- Support option `-w, --workspace-root`
- Support commands `pnpm patch <pkg>` and `pnpm patch-commit <path>`

feat(pnpm): improve generators and add flags

---

src/yarn.ts

A member of RedwoodJS community notice that Fig don't autocomplete redwood CLI anymore. 
After looking into recent changes, I see that suggestions are now base by the binaries. #1211 #1215 
Is also take packages from package.json into consideration for suggestion, problem is package name is not always the same as binary name. 
My suggestion is to only go with the binaries, since is more accurate of what is available. 
Whatever, I think we should only suggest subcommand from the list, otherwise this creates a lot a noise by irrelevant suggestion.
cc @fedeci

fix(yarn): Suggest subcommands with bin only 

---

src/kitty.ts

This links the ssh spec to ssh kitten completion. The ssh kitten is a thin wrapper around the ssh command (using the same flags/arguments), so it should use the same completion.

feat(kitty): link ssh kitten spec

---

src/expo-cli.ts

Expo cli `--dev-client` has no args. There is no true/false value for --dev-client, it's a toggle to tell Expo CLI to start the application via the Development Client without building the app like `expo run:android` or `expo run:ios` would.

fix(expo): --dev-client prompting for true or false

---

src/npx.ts

This PR fixes the wrong urls to the some of the icons (tailwindcss, nuxi, eslint) like it was on the screenshot below.

fix: some icons in npx specs now being showed

---

src/aliases.ts

This PR is to add the `aliases` autocompletion spec.
Closes #1785
Signed-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

feat: add `aliases` completion spec

---

src/elm-format.ts

**Feature**: Support for [elm-format](https://github.com/avh4/elm-format)
Support all of the publicly shown elm-format commands as of version 0.8.5.

feat: add `elm-format` completion spec

---

src/elm-review.ts

**Chore**: Update to the latest version of [elm-review](https://github.com/jfmengels/node-elm-review)
**Added:** The following flags/options
- `--fix-limit=N`
- `--extract`
- `--benchmark-info`
- `--no-color`

chore: update `elm-review` completion spec

---

src/brew.ts

This PR adds `alias` subcommand to brew.
Closes #1790

feat(brew): add alias subcommand

---

src/gh.ts

Add the new subcommand `set-default` to `gh repo`.
https://cli.github.com/manual/gh_repo_set-default
https://github.com/withfig/autocomplete/issues/1833

feat(gh): add repo set-default subcommand

---

src/dust.ts

This PR adds `dust` completion spec.
[dust](https://github.com/bootandy/dust): Like du but more intuitive.
Signed-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

feat: add `dust` completion spec.

---

src/klist.ts

This PR adds completion spec for `klist`
`klist` reads and displays the current tickets in the credential cache (also known as the ticket file).

feat: add `klist` completion spec

---

src/dos2unix.ts
src/unix2dos.ts

This PR will add the `dos2unix` and `unix2dos` autocompletion specs.
Closes #1795
Signed-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

feat: add `dos2unix` and `unix2dos` completion spec

---

src/brew.ts

This PR adds the `developer` subcommand to the `brew` spec.
Control Homebrew's developer mode. When developer mode is enabled, brew update will update Homebrew to the latest commit on the master branch instead of the latest stable version, along with other behavior changes.
Signed-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>

feat(brew): add `developer` subcommand.

---

src/goto.ts

This PR adds completion spec for [goto](https://github.com/iridakos/goto).
goto: Bash tool for navigation to aliased directories with auto-completion.
*Usage*
```shell
> goto --help                                                                                                                                                                 
usage: goto [<option>] <alias> [<directory>]
default usage:
goto <alias> - changes to the directory registered for the given alias
OPTIONS:
-r, --register: registers an alias
goto -r|--register <alias> <directory>
-u, --unregister: unregisters an alias
goto -u|--unregister <alias>
-p, --push: pushes the current directory onto the stack, then performs goto
goto -p|--push <alias>
-o, --pop: pops the top directory from the stack, then changes to that …
```

feat: add `goto` completion spec

---

src/elm-json.ts
src/elm.ts

**Feature**: Support for [elm-json](https://github.com/zwilias/elm-json)
Support all of the publicly shown elm-json commands as of version 0.2.13.

feat: add `elm-json` completion spec

---

src/k9s.ts

It is convenient for users to list all namespaces when using the `--namespace` option in the `k9s` command.
Closes https://github.com/withfig/autocomplete/issues/1755

feat: search namespace for k9s

---

src/aws/ec2.ts

No param named `subnet-ids` exists for this command, it is called `subnet-id`.
Docs: https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-route-table.html

fix(aws-ec2): `associate-route-table` `subnet-id` param

---

src/@usermn/sdc/0.0.0.ts

Looks like I forgot to update the workflow to remove the v. Oops.

fix(@usermn/sdc): remove v in version 0.0.7

---

src/jenv.ts

Made the argument of `jenv exec` as a command so fig will autocomplete the command properly.

fix(jenv): make the argument of `jenv exec` as command

---

src/xxd.ts

This PR adds completion spec for `xxd`
`xxd` creates a hex dump of a given file or standard input.  It can also convert a hex dump back to its original binary form.  Like uuencode(1) and uudecode(1), it allows the transmission of binary data in a 'mail-safe' ASCII representation but has the advantage of decoding to standard output.

feat: add `xxd` completion spec

---

src/iconv.ts

This PR adds completion spec for `iconv` command.
Usage of `iconv`
```shell
$ iconv --help                                                                                                                                          
Usage: iconv [OPTION...] [-f ENCODING] [-t ENCODING] [INPUTFILE...]
or:    iconv -l
Converts text from one encoding to another encoding.
Options controlling the input and output format:
-f ENCODING, --from-code=ENCODING
the encoding of the input
-t ENCODING, --to-code=ENCODING
the encoding of the output
Options controlling conversion problems:
-c                          discard unconvertible characters
--unicode-subst=FORMATSTRING
substitution for unconvertible Unicode characters
--byte-subst=FORMATSTRING   substitution for unconvertible bytes …
```

feat: add `iconv` completion spec.

---

src/sls.ts

This PR adds `sls` completion spec.
`sls` is a shorthand for the same [serverless](https://github.com/withfig/autocomplete/blob/master/src/serverless.ts).

feat: add sls completion spec

---

src/xc.ts

Just started using a nifty new tool [xc](https://github.com/joerdav/xc) to run scripts straight from the `README.md`, however, I missed being able to have autocomplete for scripts defined in a `package.json`. 
Thank you Fig for your tool! I can't look back to a terminal without autocomplete, so I guess its time to contribute!
Let me know if there is anything else I can do. I was unsure if I picked the correct pattern for dynamic sub-commands since it has to pick them up from your readme. And I wasn't sure if I applied the options that were command specific in the right location, vs you can run the command with no arguments and it will list what subcommands are available.

feat(xc): add xc autocomplete

---

src/nx.ts

The Nx.dev CLI had some changes and the `workspace.json` file is deprecated in Nx.dev and was spliced into multiple `project.json` files a time ago with a migration.
These `project.json` files are everywhere in the repository and has information about the project itself, his targets and the targets configuration.
This script now uses all this information to help fill out the command as comfy as possible.
The old `workspace.json` file is still supported.

feat(nx): add support for project json

---

src/space.ts

Create the specs for the [Deta Space CLI](https://github.com/deta/space-cli) at its latest commit [`aa93f14`](https://github.com/deta/space-cli/commit/aa93f1476e56268fab0c4444db1e6326feb8f59f). 
I just used the [Fig cobra integration](https://github.com/withfig/autocomplete-tools/tree/main/integrations/cobra) like this, all the fields and descriptions seemed in place: 
```
package cmd
import (
cobracompletefig "github.com/withfig/autocomplete-tools/integrations/cobra"
)
func init() {
rootCmd.AddCommand(cobracompletefig.CreateCompletionSpecCommand())
}
```
Pinging @rohanshiva @abdelhai @aavshr @BetaHuhn if you wanna review the spec or integrate the Cobra integration in the CLI for future releases ☺️ 
**Additional info**

feat: create `space` CLI spec

---

src/dbt.ts

dbt replaced the `--models/-m` option with `--select/-s`. See their docs here: https://docs.getdbt.com/reference/node-selection/syntax
Example showing `--models/-m` is not compatible with `dbt run`
```shell
❯ dbt build -m dim_users
usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d] [--log-format {text,json,default}] [--no-write-json]
[--use-colors | --no-use-colors] [--printer-width PRINTER_WIDTH]
[--warn-error | --warn-error-options WARN_ERROR_OPTIONS] [--no-version-check] [--partial-parse | --no-partial-parse]
[--use-experimental-parser] [--no-static-parser] [--profiles-dir PROFILES_DIR] [--no-anonymous-usage-stats] [-x] [-q]
[--no-print] [--cache-selected-only | --no-cache-selected-only]
{docs,source,init,clean,debug,deps,list,ls,build,snapshot,run,compile,parse,test,seed,run-oper …
```

fix(dbt): remove non-existent `--models` option

---

src/@wordpress/create-block.ts
src/npx.ts

Adds completion for `npx @wordpress/create-block`:
```
➜ npx @wordpress/create-block --help
Usage: wp-create-block [options] [slug]
Generates PHP, JS and CSS code for registering a WordPress plugin with blocks.
[slug] is optional. When provided, it triggers the quick mode where it is used as the block slug used for its identification, the output location for scaffolded files, and the name of the WordPress plugin.The rest of the configuration is set to all default values unless overridden with some options listed below.
Options:
-V, --version                output the version number
-t, --template <name>        project template type name; allowed values: "standard", "es5",
the name of an external npm package, or the path to a local
directory (default: "standard")
--namespace <value> …
```

feat: add completion for `@wordpress/create-block`

---

src/railway.ts

See https://github.com/railwayapp/cliv3/issues/6

fix(railway): verbose/version shorthands

---

src/k6.ts

Fix #1921 missing version flag, along that version missing, saw three more that were missing and added them.
-  Scale
-  Stats
- Status 
- Version
I didn't make this one from scratch, just followed the pattern that was created before.
Hope everything is correct, any issues, please let me know.

feat(k6): add missing flags

---

src/np.ts

Basic implementation of the spec for `np`. Still needs generators for versioning and branches I believe, but all options and arguments are here.

feat: add np spec

---

src/cdk.ts

We have added some additional AWS CDK subcommands compared to the current implementation.
Here is the latest list of subcommands.
```sh
cdk -h
Usage: cdk -a <cdk-app> COMMAND
Commands:
cdk list [STACKS..]             Lists all stacks in the app      [aliases: ls]
cdk synthesize [STACKS..]       Synthesizes and prints the CloudFormation
template for this stack       [aliases: synth]
cdk bootstrap [ENVIRONMENTS..]  Deploys the CDK toolkit stack into an AWS
environment
cdk deploy [STACKS..]           Deploys the stack(s) named STACKS into your
AWS account
cdk import [STACK]              Import existing resource(s) into the given
STACK
cdk watch [STACKS..]            Shortcut for 'deploy --watch'
cdk destroy [STACKS..]          Destroy the stack(s) named STACKS
cdk diff [STACKS..] …
```

feat(cdk): add some subcommand specs

---

src/serverless.ts

Feature
`serverless` compose commands are currently not-supported
Autocompletion support for `serverless` compose commands

feat: add generate spec for serverless compose

---

src/yarn.ts

yarn's `upgrade-interactive` supports `--latest` both in the [local](https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive) and [global](https://classic.yarnpkg.com/lang/en/docs/cli/global/) context, correcting this.
Tested the flag using Fig's dev mode as described in the [Getting Started guide](https://fig.io/docs/getting-started#testing-your-first-completion-spec).

feat(yarn): global upgrade-interactive --latest

---

README.md

Since `yarn.lock` was introduced in this commit https://github.com/withfig/autocomplete/commit/aec6acad7d2c286ecf930dc4321c757353ae3b66
I think docs should be updated accordingly 😄

docs: use yarn instead of npm in contribute section

---

src/adr.ts

Add complettion for [adr-tools](https://github.com/npryce/adr-tools), A command-line tool for working with a log of [Architecture Decision Records](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) (ADRs).

feat: add adr-tools completion spec

---

src/task/go-task.ts

Current Fig Generator doesn't work when having nested Taskfiles and also doesn't list root tasks. 
I have my Taskfiles split in different files, and reference them all in one file at the root of my project, current autocompletion doesn't get the tasks in my root as nor the tasks until I get into the directory containing all my Taskfiles.  
https://github.com/withfig/autocomplete/assets/20308945/5bc2d32f-86db-48cf-8eef-4b552df91439
My new approach works as expected with the root tasks while maintaining previous behavior
https://github.com/withfig/autocomplete/assets/20308945/f4661727-458c-42e0-9320-1b01c9382a1c

feat(go-task): get nested and root tasks

---

src/dart.ts

There was a typo in `--force`, and some of the template names weren't correct.

Minor fixes to `dart create`

---

src/docker-compose.ts

When using the `--profile` option in the `docker-compose` command, suggestions for the list of profiles are now provided.
In addition, some operations are common to the existing `servicesGenerator`, so they have been extracted into a function.

feat(docker-compose): add `--profile` suggestion

---

src/sam.ts

1. Add guided option
2. Fetch AWS profile name when using profile option

feat: add guided option and optimize profile option in SAM CLI

---

src/pry.ts

close #1802 
Adds support for [pry](https://github.com/pry/pry)

feat: Add pry specs 

---

src/aws.ts

feat: [aws] Add help subcommand 

---

src/stack.ts

feature: Adds Haskell stack completion spec
Completely new feature. Here's a screenshot:
Not a feature change. But an addition.
I tend to use fig a lot and thought it would be nice to have Haskell (my goto language at the moment) tools present as well. Currently I've only started with `stack` but there's also another build tool `cabal` which is pretty popular (and then ofc there's the `ghc` compiler itself which might be useful). I'll probably add those as well once this PR gets an approval. 
This is not the complete completion spec, yet. I'm in the …

feat: add stack completion spec

---

src/premake.ts

I added the spec for [premake](https://premake.github.io/).
Straight from the premake readme:
"Premake is a command line utility which reads a scripted definition of a software project, then uses it to perform build configuration tasks or generate project files for toolsets like Visual Studio, Xcode, and GNU Make. Premake's scripts are little [Lua](http://www.lua.org/) programs, so the sky's the limit!"

feat(premake): add premake spec

---

src/gt.ts

Thanks for the great CLI tool 🙌 
This PR will update the spec for the [graphite CLI](https://graphite.dev/docs/command-reference) - adding new commands or removed now unused commands.
Also cohered to the alphabetical ordering of the commands (not necessarily of all subcommands) and added a bit more type safety to the `submitOptions`.
The changes look more extreme than they actually are, most of the new commands were subcommands before.
To check against the original list, here's the link to the graphite docs: https://graphite.dev/docs/command-reference
Closes #2093

fix: update graphite (gt) cli spec

---

src/rugby.ts

Hello!
I've just added a new Fig autocomplete spec for Rugby 🏈.
https://github.com/swiftyfinch/Rugby
I read and followed [the guide](https://fig.io/docs/getting-started/contributing):

feat: add rugby completion spec

---

src/atuin.ts

Solves https://github.com/withfig/autocomplete/issues/2121

feat(atuin): add spec)

---

src/cargo.ts

Added [cargo-make](https://github.com/sagiegurari/cargo-make) completion with Makefile.toml tasks resolving.

feat(cargo-make): add cargo-make autocompletion and Makefile.toml support

---

src/cw.ts

- Add CW spec
- Fix issues with cw spec

fix(cw): Typos and generator issue

---

src/bun.ts

- add `link` subcommand with custom generator to get globally installed packages
- add `--save` option for "link" to save to package.json
- add `unlink` subcommand
- add `--canary` option to "upgrade" subcommand.
- remove `dev` subcommand (Bun no longer uses)
- add keyValueList generator for `--loader` option on `build` subcommand
- add `test` subcommand, with generator to pull in test files recognized by bun
- add `repl` subcommand
- add `build` subcommand with options
- add file suggestions to `run` subcommand
- add generator to get installed packages for `rm` subcommand
- add `--sourcemap` option with appropriate valueList
- add `--outdir` and `--outfile` options
- add `--watch` and `--hot` as global options
- add host/port suggestions for `--inspect` options
- refactor subcommand …

feat(bun): add subcommands, options, logo

---

src/git.ts

Add in missing `--show-signature` command for git

fix: add show-signature to git command

---

src/ssh.ts

Config host was not correctly resolved:
~/.ssh was not transformed into /Users/<username>/.ssh/

fix: ssh config file not resolved

---

src/z.ts

The [existing spec](https://github.com/withfig/autocomplete/blob/master/src/z.ts) for the `z` command includes folders of the cwd for [rupa/z]( https://github.com/rupa/z), but not [zoxide](https://github.com/ajeetdsouza/zoxide)'s `z`. This PR adds autocomplete suggestions for zoxide's `z` command and therefore resolves aws/codewhisperer-command-line-discussions#114.
I also added icons as per the following:
:file_folder: ... = not in zoxide history, but in cwd/pwd
:floppy_disk: ... = in zoxide history AND cwd/pwd
:floppy_disk:/... = in zoxide history, but NOT cwd/pwd (notice the leading `/` in path)
Example:
For some reason I can't seem to consistently get all of zoxide's cwd suggestions above the non-zoxide cwd suggestions. I'm using the `priority` key to try and achieve this, but it …

feat(z): include cwd folders in suggestions for zoxides `z` command

---

src/dapr.ts

Completions spec for [dapr cli](https://docs.dapr.io/reference/cli/cli-overview/)

add [dapr] spec

---

src/git.ts

Update `git stash` spec to better match https://git-scm.com/docs/git-stash#_synopsis.
This is a quick fix to remove annoying `insertValue` values for `git stash` subcommands that do not take mandatory arguments/options.
Also fixed some typos and made the `message` argument optional for `git stash create`.

feat(git): Fix stash spec

---

src/progressline.ts

https://github.com/kattouf/ProgressLine
```sh
❯ progressline --help
OVERVIEW: A command-line tool for compactly tracking the progress of piped commands.
USAGE: some-command | progressline
OPTIONS:
-s, --activity-style <activity-style>
The style of the activity indicator. (values: dots, kitt, snake; default: dots)
-l, --original-log-path <original-log-path>
Save the original log to a file.
-m, --log-matches <log-matches>
Log above progress line lines matching the given regular expressions.
-a, --log-all           Log all lines above the progress line.
-h, --help              Show help information.
```

feat: add progressline completion spec

---

src/bw.ts

The Bitwarden CLI has gained a new verb, device-approval. This PR adds support for this verb in fig/q:
https://bitwarden.com/help/cli/#device-approval
I'm using each options instead of arguments, as these seem to best allow for the required argument --organisationid after each device-approval sub-command

feat(bw): add device-approval verb support

---

src/kubectl.ts

The option was deprecated, then removed in version 1.28. Short is now the default.

fix(kubectl): Remove "--short" option from "version"

---

src/oxlint.ts

Adds support for [oxlint](https://oxc.rs/docs/guide/usage/linter.html), a next-gen JavaScript and TypeScript linter.

feat: add oxlint completions

---

src/conda.ts

This PR fixes #1083. Fixed generator extracts and returns the names of installed Conda packages from the conda list output, instead of packages, versions and build strings.
Before extracting full lines
Now extracting only package names
https://github.com/user-attachments/assets/bfedf741-8bde-482a-b051-4fd5c5243019

fix(conda): getInstalledPackages generator

---

src/oh-my-posh.ts

Fixed an error in the description of the "oh-my-posh config export" command.

Update oh-my-posh.ts to fix an error in the "config export" command description

---

src/git.ts

`date` was used as the argument name for `git clone --depth`.
The correct argument name is `depth` - https://git-scm.com/docs/git-clone#Documentation/git-clone.txt-code--depthcodeemltdepthgtem

fix(git): wrong argument name for clone --depth

---

src/ollama.ts

Introduce a completion specification for the Ollama command-line tool, enhancing user experience by providing command and argument suggestions. This includes generators for model listing and running processes.

feat: add completion specification for ollama command-line tool

---

src/ollama.ts

Master branch can't build because of lint and type check issues in ollama.ts:
1. 
```bash
Run pnpm lint
> @withfig/autocomplete@2.690.0 lint /home/runner/work/autocomplete/autocomplete
> eslint '**/*.ts' && npx prettier --check '**/*.ts' --parser typescript
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
Checking formatting...
[warn] src/ollama.ts
[warn] Code style issues found in the above file. Run Prettier with --write to fix.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```
2.
```bash
Run pnpm test
> @withfig/autocomplete@2.690.0 test /home/runner/work/autocomplete/autocomplete
> tsc --noEmit && echo 'All specs passed …
```

fix: ollama.ts lint and typecheck issues

---

src/uv.ts

1. Fixed the issue where options were not displaying.
2. Resolved issues in dependenciesGenerator.
3. Added venv options
4. Implemented commandGenerator to display commands for `uv run` ...

feat(uv): update spec

---

src/oci.ts

- Add main OCI service commands (compute, network, storage, etc.)
- Include region suggestions and global options
- Add common subcommands with required parameters
- Support authentication and output formatting options

feat(cli): add Oracle Cloud Infrastructure (OCI) CLI completion

---

.github/workflows/build.yml

Reverts withfig/autocomplete#2526 due to bug in softprops/action-gh-release. See https://github.com/softprops/action-gh-release/issues/556

Revert "build(deps): bump softprops/action-gh-release from 2.0.8 to 2.2.0"

---

src/sake.ts

- Added new args
- Specified some args types
- Added new command

feat(sake): update spec

---

src/node.ts

This can cause problems for downstream projects with more strict TS rules

fix(node): remove unused variable

---

src/git.ts

This is pretty visible, changed it to something more professional and descriptive

fix(git): use less aggressive language for description

---

src/mkdir.ts

Fixes #2589
The originals were from the man page, so it's somewhat ambiguous what the right thing to do here is.

fix(mkdir): Use lower case for arg names
